---
# handlers file for lae.netbox
- name: Restart netbox.socket
  ansible.builtin.systemd:
    name: netbox.socket
    state: restarted
    daemon_reload: true

- name: Restart netbox.service
  ansible.builtin.systemd:
    name: netbox.service
    state: restarted
    daemon_reload: true

- name: Reload netbox.service
  ansible.builtin.systemd:
    name: netbox.service
    state: reloaded

- name: Restart netbox-rqworker.service
  ansible.builtin.systemd:
    name: netbox-rqworker.service
    state: restarted
    daemon_reload: true

- name: Reload netbox-rqworker.service
  ansible.builtin.systemd:
    name: netbox-rqworker.service
    state: reloaded
