---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app druid
  namespace: &ns database
spec:
  chart:
    spec:
      chart: druid-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: datainfra
      version: 0.3.9
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
