---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
data:
  ops.json: |
    [
      {
        "uuid": "c78059d9-333d-4550-88a0-b0e897c82e8d",
        "name": "inherent_ly",
        "level": 4,
        "bypassesPlayerLimit": false
      }
    ]
