apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 15Gi
