all:
  children:
    kates:
      children:
        k3s:
          children:
            master:
              hosts:
                10.0.50.52:
                  ansible_host: 10.0.50.52
                  ansible_private_key_file: /home/angle/.ssh/id_rsa
                  ansible_python_interpreter: /usr/bin/env python3
                  ansible_user: debian
                  k3s_become: true
                  k3s_control_node: true
                  k3s_debug: false
                  k3s_etcd_datastore: true
                  k3s_install_hard_links: true
                  k3s_registration_address: '{{ kubevip_address }}'
                  k3s_release_version: v1.27.1+k3s1
                  k3s_server: &id001
                    cluster-cidr: 10.35.0.0/16
                    disable:
                    - flannel
                    - local-storage
                    - servicelb
                    - traefik
                    disable-cloud-controller: true
                    disable-network-policy: true
                    docker: false
                    etcd-expose-metrics: true
                    flannel-backend: none
                    kube-apiserver-arg:
                    - anonymous-auth=true
                    kube-controller-manager-arg:
                    - bind-address=0.0.0.0
                    kube-proxy-arg:
                    - metrics-bind-address=0.0.0.0
                    kube-scheduler-arg:
                    - bind-address=0.0.0.0
                    node-ip: '{{ ansible_host }}'
                    service-cidr: 10.45.0.0/16
                    tls-san:
                    - '{{ kubevip_address }}'
                    write-kubeconfig-mode: '644'
                  k3s_server_manifests_templates: &id002
                  - custom-calico-installation.yaml.j2
                  - custom-kube-vip-daemonset.yaml.j2
                  k3s_server_manifests_urls: &id003
                  - filename: custom-kube-vip-rbac.yaml
                    url: https://raw.githubusercontent.com/kube-vip/kube-vip/main/docs/manifests/rbac.yaml
                  - filename: custom-calico-tigera-operator.yaml
                    url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
                  - filename: custom-prometheus-alertmanagerconfigs.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
                  - filename: custom-prometheus-alertmanagers.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
                  - filename: custom-prometheus-podmonitors.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
                  - filename: custom-prometheus-probes.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
                  - filename: custom-prometheus-prometheuses.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
                  - filename: custom-prometheus-prometheusrules.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
                  - filename: custom-prometheus-servicemonitors.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
                  - filename: custom-prometheus-thanosrulers.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
                  - filename: custom-prometheus-scrapeconfigs.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
                  - filename: custom-prometheus-prometheusagents.yaml
                    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
                  k3s_use_experimental: true
                  k3s_use_unsupported_config: true
                10.0.50.53:
                  ansible_host: 10.0.50.53
                  ansible_private_key_file: /home/angle/.ssh/id_rsa
                  ansible_python_interpreter: /usr/bin/env python3
                  ansible_user: debian
                  k3s_become: true
                  k3s_control_node: true
                  k3s_debug: false
                  k3s_etcd_datastore: true
                  k3s_install_hard_links: true
                  k3s_registration_address: '{{ kubevip_address }}'
                  k3s_release_version: v1.27.1+k3s1
                  k3s_server: *id001
                  k3s_server_manifests_templates: *id002
                  k3s_server_manifests_urls: *id003
                  k3s_use_experimental: true
                  k3s_use_unsupported_config: true
                10.0.50.54:
                  ansible_host: 10.0.50.54
                  ansible_private_key_file: /home/angle/.ssh/id_rsa
                  ansible_python_interpreter: /usr/bin/env python3
                  ansible_user: debian
                  k3s_become: true
                  k3s_control_node: true
                  k3s_debug: false
                  k3s_etcd_datastore: true
                  k3s_install_hard_links: true
                  k3s_registration_address: '{{ kubevip_address }}'
                  k3s_release_version: v1.27.1+k3s1
                  k3s_server: *id001
                  k3s_server_manifests_templates: *id002
                  k3s_server_manifests_urls: *id003
                  k3s_use_experimental: true
                  k3s_use_unsupported_config: true
            node:
              hosts:
                10.0.50.62:
                  ansible_host: 10.0.50.62
                  ansible_private_key_file: /home/angle/.ssh/id_rsa
                  ansible_python_interpreter: /usr/bin/env python3
                  ansible_user: debian
                  k3s_become: true
                  k3s_debug: false
                  k3s_etcd_datastore: true
                  k3s_install_hard_links: true
                  k3s_registration_address: '{{ kubevip_address }}'
                  k3s_release_version: v1.27.1+k3s1
                  k3s_server_manifests_templates: *id002
                  k3s_server_manifests_urls: *id003
                  k3s_use_experimental: true
                  k3s_use_unsupported_config: true
                10.0.50.63:
                  ansible_host: 10.0.50.63
                  ansible_private_key_file: /home/angle/.ssh/id_rsa
                  ansible_python_interpreter: /usr/bin/env python3
                  ansible_user: debian
                  k3s_become: true
                  k3s_debug: false
                  k3s_etcd_datastore: true
                  k3s_install_hard_links: true
                  k3s_registration_address: '{{ kubevip_address }}'
                  k3s_release_version: v1.27.1+k3s1
                  k3s_server_manifests_templates: *id002
                  k3s_server_manifests_urls: *id003
                  k3s_use_experimental: true
                  k3s_use_unsupported_config: true
                10.0.50.64:
                  ansible_host: 10.0.50.64
                  ansible_private_key_file: /home/angle/.ssh/id_rsa
                  ansible_python_interpreter: /usr/bin/env python3
                  ansible_user: debian
                  k3s_become: true
                  k3s_debug: false
                  k3s_etcd_datastore: true
                  k3s_install_hard_links: true
                  k3s_registration_address: '{{ kubevip_address }}'
                  k3s_release_version: v1.27.1+k3s1
                  k3s_server_manifests_templates: *id002
                  k3s_server_manifests_urls: *id003
                  k3s_use_experimental: true
                  k3s_use_unsupported_config: true
    mc: {}
    piholes: {}
    proxie:
      children:
        prox0:
          hosts:
            pve0:
              ansible_host: 10.0.50.70
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: root
              pve_acls: &id004
              - groups:
                - api_users
                path: /storage/local
                roles:
                - PVEDatastoreAdmin
              - groups:
                - api_users
                path: /storage/local-zfs
                roles:
                - PVEDatastoreAdmin
              - groups:
                - api_users
                path: /vms
                roles:
                - PVEVMAdmin
              pve_group: proxie
              pve_groups: &id005
              - comment: Administrators of this PVE cluster
                name: Admins
              - comment: Users that represent automation tools
                name: api_users
              pve_repository_line: deb http://download.proxmox.com/debian/pve bullseye
                pve-no-subscription
              pve_roles: &id006
              - name: Monitoring
                privileges:
                - Sys.Modify
                - Sys.Audit
                - Datastore.Audit
                - VM.Monitor
                - VM.Audit
              pve_ssh_port: 22
              pve_users: &id007
              - groups:
                - api_users
                name: ansible@pve
                password: oomfie1234
              - groups:
                - api_users
                name: terraform@pve
                password: oomfie1234
              - groups:
                - api_users
                name: ansible_pve@pve
                password: oomfie1234
              - groups:
                - api_users
                name: terraform_pve@pve
                password: oomfie1234
        prox1:
          hosts:
            pve1:
              ansible_host: 10.0.50.71
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: root
              pve_acls: *id004
              pve_group: proxie
              pve_groups: *id005
              pve_repository_line: deb http://download.proxmox.com/debian/pve bullseye
                pve-no-subscription
              pve_roles: *id006
              pve_ssh_port: 22
              pve_users: *id007
        prox2:
          hosts:
            pve2:
              ansible_host: 10.0.50.72
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: root
              pve_acls: *id004
              pve_group: proxie
              pve_groups: *id005
              pve_repository_line: deb http://download.proxmox.com/debian/pve bullseye
                pve-no-subscription
              pve_roles: *id006
              pve_ssh_port: 22
              pve_users: *id007
    pxe:
      children:
        fog:
          hosts:
            10.0.50.26:
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
    ungrouped: {}
