---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: render
  namespace: gifinator
  labels:
    app: render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: render
  template:
    metadata:
      labels:
        app: render
    spec:
      containers:
        - name: render
          image: inherently/gifinator:0.0.5
          command: [/render]
          env:
            - name: MINIO_PORT
              value: "80"
            - name: MINIO_NAME
              #value: "minio-service"
              value: minio.kates.test
            - name: RENDER_PORT
              value: "8085"
          ports:
            - containerPort: 8085
