---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metabase
  namespace: &ns default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
      version: 3.7.3
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    controllers:
      metabase:
        containers:
          metabase:
            image:
              repository: metabase/metabase
              tag: "v0.54.x"
              pullPolicy: IfNotPresent
            # https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker#production-installation
            env:
              MB_DB_TYPE: "postgres"
              MB_DB_USER: "metabase"
              MB_DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: mb-secret
                    key: mb_db_pass
              MB_DB_HOST: "pg-rw.database.svc.cluster.local"
              MB_DB_PORT: "5432"
              MB_DB_DBNAME: "metabaseappdb"
    service:
      metabase:
        controller: metabase
        ports:
          http:
            port: 3000
    ingress:
      metabase:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        className: nginx
        enabled: true
        hosts:
          - host: metabase.home.inherently.xyz
            paths:
              - path: /
                pathType: ImplementationSpecific
                service:
                  identifier: metabase
                  port: http
        tls:
          - hosts:
              - metabase.home.inherently.xyz
            secretName: metabase-tls
