apiVersion: v1
stringData:
    mb_db_pass: ENC[AES256_GCM,data:IQ4N9ZO7GLecMfoEdJTSIm4nTOY5WBFonQ==,iv:esh4vjNUOo5WI6HAFxjVmMQ2zxmHI0WhncW976qnGfI=,tag:xCVGKSBDFg9tQL5/loIVAA==,type:str]
kind: Secret
metadata:
    name: mb-secret
type: Opaque
sops:
    age:
        - recipient: age1aa9sefsfad7w4hg7xqeg2pr2875vqhtsz228jz0svcssgcf99a9s8ma3nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MjdqY2xXRkxsYUIzTngx
            V3FDR1ovZEYySmJ2N2lZSExJdkpDcktIN0h3ClM5WjNiS3NIWDdiT0svNHpncHY3
            MkVyd1RqelZwUndYeG9xZ2hWM3Q4SWMKLS0tIHVYM2tFQk5oUEtmYU9LZEM4TzJt
            MlpoaExZVVZqTmZPeENYWFBxY3FPU0EKJHCMungMlFKU2FNm1STWPWKWtkuF4sp5
            G80NmmWkdQM7IneF1219MI8OnvCH7XcS9GWEsBmge17eXjdshmS3qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T12:38:32Z"
    mac: ENC[AES256_GCM,data:JfdrpU+Auu2Nuv3qj2vcCm9zHXsWTL9/2PaRC70WXQDs5xUzLBeKSKizF5OiiZ8LnouieW8aNPXuwb6RMMcJHOQRyWedhJMf0oJf2f0dJS327TbSs2BXcDS6eiBQ2Yk5pH8SbH6smpBzbaZJp6P0yMptKSB7427CCJukk86okz0=,iv:Pv8AyG0m9kg7dpKTz5eADse4q5wuJ+9BEEY9DmkpsZA=,tag:YixuANmU6IM7QVXz895Kzw==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.10.1
