---

- name: install k3s cluster
  hosts: k3s
  gather_facts: yes
  become: yes
  roles:
    - role: k3s_roles/prereq
    - role: k3s_roles/download
    - role: k3s_roles/raspberrypi
  vars:
    master_ip: "{{ hostvars[groups['k3s'][0]]['ansible_host'] | default(groups['k3s'][0]) }}"

- name: configure k3s cluster master
  hosts: "{{ hostvars[groups['k3s'][0]]['ansible_host'] | default(groups['k3s'][0]) }}"
  become: yes
  roles:
    - role: k3s_roles/k3s/master
  vars:
    master_ip: "{{ hostvars[groups['k3s'][0]]['ansible_host'] | default(groups['k3s'][0]) }}"

- name: configure k3s cluster workers
  hosts: "{{ hostvars[groups['k3s'][1:]]['ansible_host'] | default(groups['k3s'][1:]) }}"
  become: yes
  roles:
    - role: k3s_roles/k3s/node
  vars:
    master_ip: "{{ hostvars[groups['k3s'][0]]['ansible_host'] | default(groups['k3s'][0]) }}"

- name: install test k3s cluster
  hosts: k3s2
  gather_facts: yes
  become: yes
  roles:
    - role: k3s2_roles/prereq
    - role: k3s2_roles/download
    - role: k3s2_roles/raspberrypi
  vars:
    master_ip: "{{ hostvars[groups['k3s2'][0]]['ansible_host'] | default(groups['k3s2'][0]) }}"

- name: configure test k3s cluster master
  hosts: "{{ hostvars[groups['k3s2'][0]]['ansible_host'] | default(groups['k3s2'][0]) }}"
  become: yes
  roles:
    - role: k3s2_roles/k3s/master
  vars:
    master_ip: "{{ hostvars[groups['k3s2'][0]]['ansible_host'] | default(groups['k3s2'][0]) }}"

- name: configure test k3s cluster workers
  hosts: "{{ hostvars[groups['k3s2'][1:]]['ansible_host'] | default(groups['k3s2'][1:]) }}"
  become: yes
  roles:
    - role: k3s2_roles/k3s/node
  vars:
    master_ip: "{{ hostvars[groups['k3s2'][0]]['ansible_host'] | default(groups['k3s2'][0]) }}"
