---
k3s_version: v1.28.5+k3s1
token: vregmenhpatataxwristyri
user_kubectl: true
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: --tls-san 10.0.50.50 --disable=traefik --disable servicelb
extra_agent_args: ""
