---
k3s_version: "v1.28.5+k3s1"
token: "vregmenhpatataxwristyri"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: "--tls-san 10.0.50.50 --disable=traefik"
extra_agent_args: ""
...
