---
ansible_user: root
pve_group: proxmox_servers
pve_ssh_port: 22
pve_remove_subscription_warning: true
pve_cluster_enabled: true
pve_cluster_clustername: "{{ pve_group }}"
pve_manage_hosts_enabled: true
pve_groups:
  - name: admins
    comment: Administrators of this PVE cluster
  - name: api_users
    comment: Users that represent automation tools
pve_users:
  - name: ansible@pve
    password: oomfie1234
    groups:
      - api_users
  - name: terraform@pve
    password: oomfie1234
    groups:
      - api_users
pve_roles:
  - name: Monitoring
    privileges:
      - Sys.Modify
      - Sys.Audit
      - Datastore.Audit
      - VM.Monitor
      - VM.Audit
pve_acls:
  - path: /storage/local
    roles: [PVEDatastoreAdmin]
    groups:
      - api_users
  - path: /storage/local-lvm
    roles: [PVEDatastoreAdmin]
    groups:
      - api_users
  - path: /vms
    roles: [PVEVMAdmin]
    groups:
      - api_users
pve_storages:
  - name: proxmox-nfs
    type: nfs
    content: [images, iso, backup]
    server: 10.0.50.100
    export: /mnt/tank-z1/nfs-proxmox
