---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-lister-pvc
  namespace: lister
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 8Gi
