---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cnpg
  namespace: &ns database
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: 0.23.2
  interval: 10m0s
  releaseName: *app
  targetNamespace: *ns
