apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:jAdwpA==,iv:jVgcg2F6upi0JU8/KKBLvPI14yPGC170VBWvBL4N7Js=,tag:5mNCQtSPuzPteAXDklzwbg==,type:str]
    password: ENC[AES256_GCM,data:326S0Q==,iv:2cdenjDTjyMgvGfKCK1O5cKSnBeyhrj0zpEN5hx9upo=,tag:7rGnUVRulXqLBWkElZe6IQ==,type:str]
kind: Secret
metadata:
    name: appdb-test
    namespace: default
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aa9sefsfad7w4hg7xqeg2pr2875vqhtsz228jz0svcssgcf99a9s8ma3nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheVdjcWJJTmdVeTJJbWFQ
            REFHdVNRaTdkZ1NIZmc5a2JqZ1hGRWh5cHl3Ck1SWmlkOUlQeENKUW5iVC9EbXpL
            bWRlSTNxNWoxK20ybTU3b0FCcEI3OGcKLS0tIFdOSG1ZZVlCU0YydHk1dmNrU20v
            bW1HRlJpZlpLbFdHUzBMaWFjODNuQlUKHmARWN+uYwmWFUe+oIN5qpZ+T4nCuCdd
            HmSwFxgOBY+IMVouEGFBJdk4FAS0NCo5JQaSLL6BZMFmmq/KDnuKjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T21:08:21Z"
    mac: ENC[AES256_GCM,data:Y94kp4ou2bn3LtlKxQFM16Odpu0F4/v3tG0L7AhzNRomtYMP+aiqF9AUh24BPHf3XDgVS6w5eevwp8S+Gw688xI6u/xzDCG9r3BSQVECLalmxIQ5+G12FeOrXybwQ4AI/eyuJB/H32uQMmsYQwuu0tLN6EC6DL9Z7iRttfKrUYQ=,iv:mRcAuKo9yjeFAAo/5beQr34HBon5URFKk6kFtOc89ME=,tag:kqSPtlD/BA/0nwScfU+ANw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.4
