---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lister
  namespace: &ns default
spec:
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lister
      version: 0.3.5
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    secretName: *app
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      className: nginx
      enabled: true
      hosts:
        - host: lister.home.inherently.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - lister.home.inherently.xyz
          secretName: lister-tls
