apiVersion: v1
stringData:
    PG_URL: ENC[AES256_GCM,data:nudK08nCCikQIub4UIAQlqQq/WDbhfVUATjwMi+A1kgCSMmJOBluV1vDyw8vVLxERSQh2v7XYhBDiVXkifS8DF7crj2UDFGdcUlDGSFidpkeJe0OajFMjHAJFqmcAgo=,iv:PnIVSbOfpmfz/zovZzwYvmAxL6KprcQ8RWz35tuefb4=,tag:suK3vWzz5tf9+bfPBskQEQ==,type:str]
kind: Secret
metadata:
    name: lister
type: Opaque
sops:
    age:
        - recipient: age1aa9sefsfad7w4hg7xqeg2pr2875vqhtsz228jz0svcssgcf99a9s8ma3nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MjdqY2xXRkxsYUIzTngx
            V3FDR1ovZEYySmJ2N2lZSExJdkpDcktIN0h3ClM5WjNiS3NIWDdiT0svNHpncHY3
            MkVyd1RqelZwUndYeG9xZ2hWM3Q4SWMKLS0tIHVYM2tFQk5oUEtmYU9LZEM4TzJt
            MlpoaExZVVZqTmZPeENYWFBxY3FPU0EKJHCMungMlFKU2FNm1STWPWKWtkuF4sp5
            G80NmmWkdQM7IneF1219MI8OnvCH7XcS9GWEsBmge17eXjdshmS3qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T13:09:16Z"
    mac: ENC[AES256_GCM,data:XlXrf2eHfiJCf+WmyuSKraM1ugoKZpm4ipKDY3RvS4St21vzVw8dMTyiDLEeqfgpir1PJxvy8Lt182iqZYl8emi5ygir36vSUW9ghh6pYyed/Wou7KD5bshAPyJv+onkNos6MRkyPTFuKsmxQ0FwtMNJF+cojT0s0NSkvyKwPlU=,iv:/9cj8ubTs/JxPaiRIeFyj+2CmimsqWbsHpU7fdbCgg4=,tag:ovM0PS/RnJ3pNuRzoLygbg==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.10.1
