apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
resources:
  - ./cert-manager/ks.yaml
  - ./metallb/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./external-dns/ks.yaml
  - ./cloudflared/ks.yaml
