---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.latest.gitlab-ci.yml

include:
  - template: Terraform/Base.latest.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.latest.gitlab-ci.yml

variables:
  TF_ROOT: terraform
  TF_STATE_NAME: homelab-cluster

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

kics-iac-sast:
  stage: validate

terraform_fmt:
  tags: [terraform]
  extends: .terraform:fmt
  needs: []

terraform_validate:
  tags: [terraform]
  extends: .terraform:validate
  needs: []

terraform_plan:
  tags: [terraform]
  extends: .terraform:build
  needs: [terraform_fmt, terraform_validate]
  environment:
    name: $TF_STATE_NAME
    action: prepare

terraform_apply:
  tags: [terraform]
  extends: .terraform:deploy
  needs: [terraform_plan]
  dependencies: [terraform_plan]
  environment:
    name: $TF_STATE_NAME
    action: start

terraform_destroy:
  tags: [terraform]
  extends: .terraform:destroy
  needs: [terraform_plan]
  dependencies: [terraform_plan]
  environment:
    name: $TF_STATE_NAME
