# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.latest.gitlab-ci.yml

include:
  - template: Terraform/Base.latest.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.latest.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

fmt single:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-single
  extends: .terraform:fmt
  needs: []

validate single:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-single
  extends: .terraform:validate
  needs: []

build single:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-single
  extends: .terraform:build
  environment:
    name: $TF_STATE_NAME
    action: prepare

deploy single:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-single
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
    action: start

fmt cluster:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-cluster
  extends: .terraform:fmt
  needs: []

validate cluster:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-cluster
  extends: .terraform:validate
  needs: []

build cluster:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-cluster
  extends: .terraform:build
  environment:
    name: $TF_STATE_NAME
    action: prepare

deploy cluster:
  tags: [terraform]
  variables:
    TF_ROOT: terraform/proxmox-cluster
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
    action: start
