---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.latest.gitlab-ci.yml

# TODO: replace terraform in here with opentofu: https://gitlab.com/components/opentofu
include:
  - component: gitlab.com/components/opentofu/full-pipeline@0.15.0
    inputs:
      # The version must currently be specified explicitly as an input,
      # to find the correctly associated images. # This can be removed
      # once https://gitlab.com/gitlab-org/gitlab/-/issues/438275 is solved.
      version: 0.15.0
      opentofu_version: 1.6.1
      root_dir: terraform
      state_name: homelab-cluster
      auto_apply: "true"

stages: [validate, build, deploy, cleanup]
ansible_lint:
  tags: [ansible]
  stage: validate
  image: alpine:latest
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  artifacts:
    when: always
    reports:
      junit: ansible/ansible-lint.xml
  before_script:
    - apk update
    - apk add --no-cache ansible ansible-lint py3-pip
    - pip install --break-system-packages ansible-lint-junit
  script:
    - cd ansible
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install vkhitrin.libguestfs
    - ansible-galaxy collection install prometheus.prometheus
    - ansible-lint -f pep8 --nocolor | ansible-lint-junit -o ansible-lint.xml

ansible_syntax_check:
  tags: [ansible]
  stage: validate
  image: alpine:latest
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  before_script:
    - apk update
    - apk add --no-cache ansible openssh
  script:
    - cd ansible
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install vkhitrin.libguestfs
    - ansible-galaxy collection install prometheus.prometheus
    - ansible-playbook -i inventory/inventory.yml --syntax-check site.yml

ansible_check_diff:
  tags: [ansible]
  stage: validate
  image: alpine:latest
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  before_script:
    - apk update
    - apk add --no-cache ansible ansible-lint openssh
  script:
    - cd ansible
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install vkhitrin.libguestfs
    - ansible-galaxy collection install prometheus.prometheus
    - ansible-playbook -i inventory/inventory.yml --check --diff site.yml

fmt:
  tags: [terraform]
validate:
  tags: [terraform]
plan:
  tags: [terraform]
  needs:
    - fmt
    - validate

apply:
  tags: [terraform]
  needs:
    - plan

destroy:
  tags: [terraform]
  needs: []
delete-state:
  tags: [terraform]
