- name: Install and configure ProxMox
  hosts: pve
  become: True
  roles:
    - role: geerlingguy.ntp
    - role: lae.proxmox

  tasks:
    - name: install essentials
      apt:
        name:
          - vim
          - tmux
          - htop
          - stterm
          - qemu-guest-agent
          - python3
          - python3-apt
          - nfs-common
          - nfs4-acl-tools
          - libguestfs-tools
        state:
          present

    # Debian 11
    - name: Download debian 11 generic cloud image
      get_url:
        url: https://cloud.debian.org/images/cloud/bullseye/20231013-1532/debian-11-genericcloud-amd64-20231013-1532.qcow2
        dest: /root/debian-11-amd64.qcow2
        checksum: sha512:651051664551425a1b731d5cb90cee33819ab8a3f955780efdb5e7045b057ec350345993a673f23a75c30aa2cb41409d0b6b5222a4f930028beaaa3c052ec0ec
        mode: '0644'
        owner: root
        group: root

    - name: Add qemu-guest-agent and remove unattended-upgrades
      shell:
        chdir: /root/
        cmd: virt-customize -a ./debian-11-amd64.qcow2 --install qemu-guest-agent --uninstall unattended-upgrades

    - name: Download debian 11 template vm script
      copy:
        src: setup-debian-11-cloudinit.sh
        dest: /root/setup-debian-11-template.sh
        mode: '0755'
        owner: root
        group: root

    - name: Run debian 11 template vm script
      shell:
        chdir: /root/
        cmd: /root/setup-debian-11-template.sh

    # Debian 12
    - name: Download debian 12 generic cloud image
      get_url:
        url: https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-genericcloud-amd64-20231013-1532.qcow2
        dest: /root/debian-12-amd64.qcow2
        checksum: sha512:6b55e88b027c14da1b55c85a25a9f7069d4560a8fdb2d948c986a585db469728a06d2c528303e34bb62d8b2984def38fd9ddfc00965846ff6e05b01d6e883bfe
        mode: '0644'
        owner: root
        group: root

    - name: Add qemu-guest-agent and remove unattended-upgrades
      shell:
        chdir: /root/
        cmd: virt-customize -a ./debian-12-amd64.qcow2 --install qemu-guest-agent --uninstall unattended-upgrades

    - name: Download debian 12 template vm script
      copy:
        src: setup-debian-12-cloudinit.sh
        dest: /root/setup-debian-12-template.sh
        mode: '0755'
        owner: root
        group: root

    - name: Run debian 12 template vm script
      shell:
        chdir: /root/
        cmd: /root/setup-debian-12-template.sh
