---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubecraft-proxy
  namespace: &ns default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
      version: 3.7.3
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    controllers:
      kubecraft-proxy:
        containers:
          kubecraft-proxy:
            image:
              repository: kubecraft/kubecraft-proxy
              tag: 0.1.0
              pullPolicy: IfNotPresent
    service:
      kubecraft-proxy:
        controller: kubecraft-proxy
        ports:
          minecraft:
            port: 25565
          grpc:
            port: 65535
