---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gifinator
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: inherently/gifinator:0.0.5
          command: [/frontend]
          env:
            - name: FRONTEND_TEMPLATES_DIR
              value: /templates
            - name: FRONTEND_STATIC_DIR
              value: /static
            - name: FRONTEND_PORT
              value: "8090"
            - name: GIFCREATOR_NAME
              value: gifcreator-service
            - name: GIFCREATOR_PORT
              value: "8082"
          ports:
            - containerPort: 8090
