apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifinator-frontend-deployment
  namespace: gifinator
  labels:
    app: gifinator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifinator-frontend
  template:
    metadata:
      labels:
        app: gifinator-frontend
    spec:
      containers:
      - name: gifinator-frontend
        image: inherently/gifinator:0.0.3
        env:
        - name: FRONTEND_TEMPLATES_DIR
          value: /templates
        - name: FRONTEND_STATIC_DIR
          value: /static
        - name: FRONTEND_PORT
          value: 8090
        - name: GIFCREATOR_NAME
          value: gifcreator-server
        - name: GIFCREATOR_PORT
          value: 8082
        ports:
        - containerPort: 8090
