---
- name: Install Certbot.
  ansible.builtin.package:
    name: "{{"
    state: present
    cmd: certbot_package }}
- name: Set Certbot script variable.
  ansible.builtin.set_fact:
    certbot_script: "{{ certbot_package }}"
