apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: appdb
  namespace: database
spec:
  instances: 2
  storage:
    size: 20Gi
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "pg-rw"
            spec:
              type: LoadBalancer
              loadBalancerIP: 10.0.50.160
        - selectorType: ro
          serviceTemplate:
            metadata:
              name: "pg-ro"
            spec:
              type: LoadBalancer
              loadBalancerIP: 10.0.50.161
    roles:
      - name: angle
        ensure: present
        comment: personal admin user
        login: true
        superuser: true
        passwordSecret:
          name: appdb-angle
      - name: test
        ensure: present
        comment: test user
        login: true
        passwordSecret:
          name: appdb-test
      - name: lister
        ensure: present
        comment: user for lister app
        login: true
        passwordSecret:
          name: appdb-lister
      - name: metabase
        ensure: present
        comment: user for metabase app
        login: true
        passwordSecret:
          name: appdb-metabase
      - name: forgejo
        ensure: present
        comment: user for forgejo app
        login: true
        passwordSecret:
          name: appdb-forgejo
