---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metallb
  namespace: &ns network
spec:
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: 0.14.9
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    controller:
      enabled: true
    crds:
      enabled: true
      validationFailurePolicy: Fail
    frrk8s:
      enabled: false
      external: false
    rbac:
      create: true
    speaker:
      enabled: true
      frr:
        enabled: false
      ignoreExcludeLB: true
