---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: 6.7.0
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: podinfo
  targetNamespace: podinfo
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      enabled: true
      hosts:
      - host: podinfo.home.inherently.xyz
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - podinfo.home.inherently.xyz
        secretName: podinfo-staging-tls
    ui:
      color: '#440044'
      message: inherent podinfo
