# Permanlink: https://raw.githubusercontent.com/stefanprodan/podinfo/08238eada746de8114efa36d36e2aa93bd76cfab/charts/podinfo/values.yaml

ui:
  color: "#440044"
  message: "inherent podinfo"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: podinfo.home.inherently.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: podinfo-tls
    hosts:
      - podinfo.home.inherently.xyz
