---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app strimzi-kafka-operator
  namespace: &ns analytics
spec:
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.46.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: *ns
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
