---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lister
  namespace: flux-system
spec:
  chart:
    spec:
      chart: lister
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lister
      version: 0.3.5
  interval: 10m0s
  releaseName: lister
  targetNamespace: lister
  values:
    secretName: lister
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      className: nginx
      enabled: true
      hosts:
      - host: lister.home.inherently.xyz
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - lister.home.inherently.xyz
        secretName: lister-tls
