---
- name: Obtain the version of the running PowerDNS instance
  shell: |
    pdns_server --version 2>&1 | awk '/PowerDNS Authoritative/{print $7}'
  register: _pdns_version
  check_mode: false
  changed_when: false

- name: Export the running PowerDNS instance version to a variable
  set_fact:
    _pdns_running_version: "{{ _pdns_version['stdout'] | regex_replace('-[.\\d\\w]+$', '') }}"
