---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: 0.21.6
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: cnpg
  targetNamespace: cnpg-system
  values:
    rbac:
      aggregateClusterRoles: false
