all:
  children:
    influxdb:
      hosts:
        10.0.50.28:
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
    k3s_cluster:
      children:
        agent:
          hosts:
            10.0.50.61:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_agent: &id001
                node-ip: '{{ ansible_host }}'
              k3s_control_node: false
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
            10.0.50.62:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_agent: *id001
              k3s_control_node: false
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
            10.0.50.63:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_agent: *id001
              k3s_control_node: false
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
            10.0.50.64:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_agent: *id001
              k3s_control_node: false
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
        server:
          hosts:
            10.0.50.51:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_control_node: true
              k3s_server: &id002
                cluster-cidr: 10.35.0.0/16
                disable:
                - flannel
                - local-storage
                - servicelb
                - traefik
                disable-cloud-controller: true
                disable-network-policy: true
                docker: false
                etcd-expose-metrics: true
                flannel-backend: none
                kube-apiserver-arg:
                - anonymous-auth=true
                kube-controller-manager-arg:
                - bind-address=0.0.0.0
                kube-proxy-arg:
                - metrics-bind-address=0.0.0.0
                kube-scheduler-arg:
                - bind-address=0.0.0.0
                node-ip: '{{ ansible_host }}'
                service-cidr: 10.45.0.0/16
                tls-san:
                - '{{ kubevip_address }}'
                write-kubeconfig-mode: '644'
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
            10.0.50.52:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_control_node: true
              k3s_server: *id002
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
            10.0.50.53:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              api_endpoint: '{{ hostvars[groups[''server''][0]][''ansible_host'']
                | default(groups[''server''][0]) }}'
              extra_agent_args: ''
              extra_server_args: ''
              k3s_control_node: true
              k3s_server: *id002
              k3s_version: v1.28.5+k3s1
              token: vregmenhpatataxwristyri
    mysql:
      hosts:
        10.0.50.21:
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
    pihole:
      hosts:
        10.0.50.2:
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
    postgres:
      hosts:
        10.0.50.20:
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
    proxie:
      hosts:
        pve0:
          ansible_host: 10.0.50.70
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          ntp_timezone: Europe/Athens
          pve_acls: &id003
          - groups:
            - api_users
            path: /storage/local
            roles:
            - PVEDatastoreAdmin
          - groups:
            - api_users
            path: /storage/local-lvm
            roles:
            - PVEDatastoreAdmin
          - groups:
            - api_users
            path: /vms
            roles:
            - PVEVMAdmin
          pve_cluster_clustername: '{{ pve_group }}'
          pve_cluster_enabled: true
          pve_group: proxie
          pve_groups: &id004
          - comment: Administrators of this PVE cluster
            name: admins
          - comment: Users that represent automation tools
            name: api_users
          pve_manage_hosts_enabled: true
          pve_remove_subscription_warning: true
          pve_roles: &id005
          - name: Monitoring
            privileges:
            - Sys.Modify
            - Sys.Audit
            - Datastore.Audit
            - VM.Monitor
            - VM.Audit
          pve_ssh_port: 22
          pve_storages: &id006
          - content:
            - images
            - iso
            - backup
            export: /mnt/tank-z1/nfs-proxmox
            name: proxmox-nfs
            server: 10.0.50.100
            type: nfs
          pve_users: &id007
          - groups:
            - api_users
            name: ansible@pve
            password: oomfie1234
          - groups:
            - api_users
            name: terraform@pve
            password: oomfie1234
          template_vmid: 9001
        pve1:
          ansible_host: 10.0.50.71
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          ntp_timezone: Europe/Athens
          pve_acls: *id003
          pve_cluster_clustername: '{{ pve_group }}'
          pve_cluster_enabled: true
          pve_group: proxie
          pve_groups: *id004
          pve_manage_hosts_enabled: true
          pve_remove_subscription_warning: true
          pve_roles: *id005
          pve_ssh_port: 22
          pve_storages: *id006
          pve_users: *id007
          template_vmid: 9002
        pve2:
          ansible_host: 10.0.50.72
          ansible_private_key_file: /home/angle/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          ntp_timezone: Europe/Athens
          pve_acls: *id003
          pve_cluster_clustername: '{{ pve_group }}'
          pve_cluster_enabled: true
          pve_group: proxie
          pve_groups: *id004
          pve_manage_hosts_enabled: true
          pve_remove_subscription_warning: true
          pve_roles: *id005
          pve_ssh_port: 22
          pve_storages: *id006
          pve_users: *id007
          template_vmid: 9003
    pxe:
      children:
        fog:
          hosts:
            10.0.50.26:
              ansible_private_key_file: /home/angle/.ssh/id_ed25519
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
