---
all:
  children:
    aptcache_servers:
      hosts:
        aptcache:
          ansible_host: 10.0.50.9
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    desktops:
      hosts:
        arch_main:
          ansible_host: 10.0.20.49
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: angle
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    fog_servers:
      hosts:
        fog:
          ansible_host: 10.0.50.7
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    gitlab_servers:
      hosts:
        gitlab:
          ansible_host: 10.0.50.45
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          cloudflare_api_token: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            37313863346536373662633439316335306631373162323262613039613435646633353935373730
            6262643665343634336231393336653864313261353233630a643661373561323130613266333139
            63373434313634613737333864376437316364393836613338383039616238303466653265303336
            6130653565616565610a623861336666313435636132323835306534303337393565313862363161
            30393337373539343830653830356330313161303435373461633234316434316538623835663562
            3430363730393532333166643732623532323332623338343966
          ntp_timezone: Europe/Athens
    grafana_servers:
      hosts:
        grafana:
          ansible_host: 10.0.50.30
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    influxdb_servers:
      hosts:
        influxdb:
          ansible_host: 10.0.50.32
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    mysql_servers:
      hosts:
        mysql:
          ansible_host: 10.0.50.21
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    netbox_servers:
      hosts:
        netbox:
          ansible_host: 10.0.50.112
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    observium_servers:
      hosts:
        observium:
          ansible_host: 10.0.50.34
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    pihole_servers:
      hosts:
        pihole:
          ansible_host: 10.0.50.2
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    postgres_servers:
      hosts:
        postgres:
          ansible_host: 10.0.50.20
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          cloudflare_api_token: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            33663731643431393965336636656266326634366334623265383038383232393165393233643964
            6462376130383233633864363131653638363563323962380a383236663630636234626465646362
            33313132383531316239383766623561653430373664363061653263633639346365323331386232
            3030383732333463620a303635636632643338363063643065333131373065653563353737336662
            37353133346630346361663539323565396237643139653034386234383364346237613432633332
            3030343138303130346362653664346337613539633663613936
          ntp_timezone: Europe/Athens
    powerdns_servers:
      hosts:
        powerdns:
          ansible_host: 10.0.50.5
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    prometheus_servers:
      hosts:
        prometheus:
          ansible_host: 10.0.50.31
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    proxmox_servers:
      hosts:
        pve0:
          ansible_host: 10.0.50.70
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
          template_vmid: 9001
          template_vmid2: 9004
        pve1:
          ansible_host: 10.0.50.71
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
          template_vmid: 9002
          template_vmid2: 9005
        pve2:
          ansible_host: 10.0.50.72
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
          template_vmid: 9003
          template_vmid2: 9006
    sentry_servers:
      hosts:
        sentry:
          ansible_host: 10.0.50.38
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
    stepca_servers:
      hosts:
        step_ca:
          ansible_host: 10.0.50.19
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          apt_proxy: http://10.0.50.9:3142
          ntp_timezone: Europe/Athens
          step_ca_version: "0.25.2"
