apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifcreator-worker-deployment
  namespace: gifinator
  labels:
    app: gifcreator-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifcreator-worker
  template:
    metadata:
      labels:
        app: gifcreator-worker
    spec:
      containers:
      - name: gifcreator-worker
        image: #TODO: fill in
        command: ["/go/bin/gifcreator", "-worker"]
        env:
        - name: REDIS_NAME
          value: redis
        - name: REDIS_PORT
          value: 6379
        - name: RENDER_NAME
          value: render
        - name: RENDER_PORT
          value: 8080
        - name: GIFCREATOR_PORT
          value: 8081
        ports:
        - containerPort: 8082
