apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifcreator-worker-deployment
  namespace: gifinator
  labels:
    app: gifcreator-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifcreator-worker
  template:
    metadata:
      labels:
        app: gifcreator-worker
    spec:
      containers:
      - name: gifcreator-worker
        image: inherently/gifinator:0.0.3
        command: ["/gifcreator", "-worker"]
        env:
        - name: RENDER_NAME
          value: "render-service"
        - name: RENDER_PORT
          value: "8080"
        - name: REDIS_NAME
          value: "gifinator-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: GIFCREATOR_PORT
          value: "8081"
        - name: MINIO_NAME
          value: "gifinator-minio"
        ports:
        - containerPort: 8082
