---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openebs
  namespace: &ns storage
spec:
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 4.1.3
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    localpv-provisioner:
      hostpathClass:
        enabled: false
      rbac:
        create: true
    lvm-localpv:
      crds:
        csi:
          volumeSnapshots:
            enabled: false
        lvmLocalPv:
          enabled: false
    mayastor:
      crds:
        enabled: false
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        clusterDomain: cluster.local
      io_engine:
        envcontext: iova-mode=pa
      localpv-provisioner:
        enabled: false
        hostpathClass:
          enabled: false
      loki-stack:
        enabled: false
        promtail:
          enabled: false
        rbac:
          create: false
      obs:
        callhome:
          enabled: false
      storageClass:
        default: false
        enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: true
    zfs-localpv:
      crds:
        csi:
          volumeSnapshots:
            enabled: false
        zfsLocalPv:
          enabled: false
