---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifcreator-server
  namespace: gifinator
  labels:
    app: gifcreator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifcreator-server
  template:
    metadata:
      labels:
        app: gifcreator-server
    spec:
      containers:
        - name: gifcreator-server
          image: inherently/gifinator:0.0.5
          command: [/gifcreator]
          env:
            - name: RENDER_NAME
              value: render-service
            - name: RENDER_PORT
              value: "8085"
            - name: REDIS_NAME
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: GIFCREATOR_PORT
              value: "8082"
            - name: MINIO_PORT
              value: "80"
            - name: MINIO_NAME
              #value: "minio-service"
              value: minio.kates.test
            - name: SCENE_PATH
              value: /tmp/scene
          ports:
            - containerPort: 8082
