apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifcreator-server-deployment
  namespace: gifinator
  labels:
    app: gifcreator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifcreator-server
  template:
    metadata:
      labels:
        app: gifcreator-server
    spec:
      containers:
      - name: gifcreator-server
        image: inherently/gifinator:0.0.3
        command: ["/gifcreator"]
        env:
        - name: RENDER_NAME
          value: "render-service"
        - name: REDIS_NAME
          value: "gifinator-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: GIFCREATOR_PORT
          value: "8082"
        - name: MINIO_NAME
          value: "gifinator-minio"
        ports:
        - containerPort: 8081
