apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifcreator-server-deployment
  namespace: gifinator
  labels:
    app: gifcreator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifcreator-server
  template:
    metadata:
      labels:
        app: gifcreator-server
    spec:
      containers:
      - name: gifcreator-server
        image: inherently/gifinator:0.0.3
        command: ["/go/bin/gifcreator"]
        env:
        - name: REDIS_NAME
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: GIFCREATOR_PORT
          value: "8082"
        ports:
        - containerPort: 8081
