---

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ ansible_host }}"
  docker: false
  disable:
    #- flannel
    #- local-storage
    #- metrics-server
    - servicelb
    - traefik
  #flannel-backend: "none"
  #disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  cluster-cidr: 172.13.0.0/16
  service-cidr: 192.168.8.0/22
  etcd-expose-metrics: true
  kube-controller-manager-arg:
    # Required to monitor kube-controller-manager with kube-prometheus-stack
    - bind-address=0.0.0.0
  kube-proxy-arg:
    # Required to monitor kube-proxy with kube-prometheus-stack
    - metrics-bind-address=0.0.0.0
  kube-scheduler-arg:
    # Required to monitor kube-scheduler with kube-prometheus-stack
    - bind-address=0.0.0.0
  # Required to monitor etcd with kube-prometheus-stack
  kube-apiserver-arg:
    # Required for HAProxy health-checks
    - anonymous-auth=true
