apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: gifinator
spec:
  rules:
  - host: minio.kates.test
    http:
      paths:
      - path: /
        backend:
          serviceName: gifinator-minio
          servicePort: 9000
