apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: gifinator
spec:
  rules:
  - host: minio.kates.test
    http:
      paths:
      - path: /
        backend:
          serviceName: minio-service
          servicePort: 9000
  - host: console.minio.kates.test
    http:
      paths:
      - path: /
        backend:
          serviceName: minio-service
          servicePort: 9001
