---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: gifinator
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      protocol: TCP
      name: api
    - port: 9001
      protocol: TCP
      name: console
