allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: zfs-nfs
    meta.helm.sh/release-namespace: democratic-csi
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2021-07-19T22:07:14Z"
  labels:
    app.kubernetes.io/instance: zfs-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.8.3
  name: freenas-nfs-csi
  resourceVersion: "883"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/freenas-nfs-csi
  uid: db4915e0-64a4-4544-a6a8-e00366596c38
mountOptions:
- noatime
- nfsvers=4
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: controller-expand-secret-freenas-nfs-csi-zfs-nfs-democratic-csi
  csi.storage.k8s.io/controller-expand-secret-namespace: democratic-csi
  csi.storage.k8s.io/controller-publish-secret-name: controller-publish-secret-freenas-nfs-csi-zfs-nfs-democratic-cs
  csi.storage.k8s.io/controller-publish-secret-namespace: democratic-csi
  csi.storage.k8s.io/node-publish-secret-name: node-publish-secret-freenas-nfs-csi-zfs-nfs-democratic-csi
  csi.storage.k8s.io/node-publish-secret-namespace: democratic-csi
  csi.storage.k8s.io/node-stage-secret-name: node-stage-secret-freenas-nfs-csi-zfs-nfs-democratic-csi
  csi.storage.k8s.io/node-stage-secret-namespace: democratic-csi
  csi.storage.k8s.io/provisioner-secret-name: provisioner-secret-freenas-nfs-csi-zfs-nfs-democratic-csi
  csi.storage.k8s.io/provisioner-secret-namespace: democratic-csi
  fsType: nfs
provisioner: org.democratic-csi.nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
