---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./lister/ks.yaml
  - ./podinfo/ks.yaml
  - ./metabase/ks.yaml
