---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./forgejo/ks.yaml
  - ./gitlab-agent/ks.yaml
  #- ./gitlab-runner/ks.yaml
  - ./lister/ks.yaml
  - ./metabase/ks.yaml
  - ./podinfo/ks.yaml
  - ./redlib/ks.yaml
  - ./kubecraft-proxy/ks.yaml
  #- ./minecraft/ks.yaml
