---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: server-vlan-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.50.150-10.0.50.199
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - server-vlan-pool
