---
prometheus_config_flags_extra:
  web.enable-admin-api:
# https://github.com/cloudalchemy/ansible-prometheus/issues/250#issuecomment-567867296
prometheus_targets:
  node:
    - targets: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('regex_replace', '$', ':9100') | list }}"
      labels:
        env: homelab
prometheus_scrape_configs:
  - job_name: node
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
prometheus_web_config:
  tls_server_config:
    cert_file: /etc/ssl/prometheus01.home.inherently.xyz.crt
    key_file: /etc/ssl/prometheus01.home.inherently.xyz.key
