---
env:
  DRONE_SERVER_HOST: drone.kates.test

  DRONE_SERVER_PROTO: http

  DRONE_RPC_SECRET: 46269c2002c6353fbfef1d20fb40b6f0

  DRONE_GITEA_SERVER: http://gitea.kates.test

  DRONE_GITEA_CLIENT_ID: 59f72e39-f412-4ef9-bd50-ba974d86d58f

  DRONE_GITEA_CLIENT_SECRET: iaVGKxNCH6Unypqx7pm1qSPetYmRcu3L-LKwa0y3T1M=

  DRONE_LOGS_TRACE: true

  DRONE_LOGS_DEBUG: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: drone.kates.test
  annotations: {}
  hosts:
    - host: drone.kates.test
      paths:
        - /

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  annotations: {}
  existingClaim: ""
  mountPath: /data
  subPath: drone
  size: 1Gi
