---
# Redis uses a mix of sha1 and sha256 checksums.
# Determine the type of checksum based on its length and prefix the variable appropriately
- name: Set redis checksum
  ansible.builtin.set_fact:
    redis_checksum: "{{ 'sha1' if redis_checksums[redis_version] | length == 40 else 'sha256' }}:{{ redis_checksums[redis_version] }}"
  when:
    - redis_verify_checksum|bool
    - redis_checksum is not defined
    - redis_version in redis_checksums

- name: Download redis
  ansible.builtin.get_url:
    url: "{{ redis_download_url }}"
    dest: /usr/local/src/redis-{{ redis_version }}.tar.gz
    checksum: "{{ redis_checksum | default(omit) }}"
  when: not redis_tarball

- name: Upload redis
  ansible.builtin.copy:
    src: "{{ redis_tarball }}"
    dest: /usr/local/src/redis-{{ redis_version }}.tar.gz
  when: redis_tarball|default(false)

- name: Extract redis tarball
  ansible.builtin.unarchive:
    src: /usr/local/src/redis-{{ redis_version }}.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    copy: false
  when: not ansible_check_mode
