---
- ansible.builtin.include_tasks: check_vars.yml

- ansible.builtin.include_tasks: download.yml
  tags:
    - download

- ansible.builtin.include_tasks: dependencies.yml
  tags:
    - install

- ansible.builtin.include_tasks: install.yml
  tags:
    - install

- ansible.builtin.include_tasks: server.yml
  when: not redis_sentinel
  tags:
    - config

- ansible.builtin.include_tasks: sentinel.yml
  when: redis_sentinel
  tags:
    - config

- ansible.builtin.include_tasks: local_facts.yml
  when: redis_local_facts|bool
