---

- name: get dem debby boiz done up
  hosts:
    - kates
  become: true

  tasks:
    - name: upd8 every m8
      apt:
        upgrade: full
        update_cache: yes

    - name: INSTALL good packages
      apt:
        name:
          - vim
          - tmux
          - htop
          - stterm
          - qemu-guest-agent
          - python3
          - python3-apt
          - nfs-common
          - nfs4-acl-tools
        state:
          present

    - name: DELET this
      apt:
        name:
          - nano
        state:
          absent

    - name: Copy /etc/network/interfaces config
      copy:
        src: debinterfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'

    # TODO: switch this to shut down instead of reboot, run add-qga-k3s-vms.plan and then boot
    - name: rebooty the debooty
      ansible.builtin.reboot:
        reboot_timeout: 300

      #NOTE: shutdown command
      #community.general.shutdown:


...
