---

- name: get proxie moxie dressed right
  hosts: proxie
  become: true

  tasks:
    - name: remove garbo enterprise repo
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: no-sub squad gang
      copy:
        src: pve-no-sub.list
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        mode: '0644'
        owner: root
        group: root

    - name: get debbie could image
      get_url:
        #url: http://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2
        url: https://cdimage.debian.org/images/cloud/bullseye/20210814-734/debian-11-generic-amd64-20210814-734.qcow2
        dest: /root/debian-11-openstack-amd64.qcow2
        checksum: sha512:ed680265ce925e3e02336b052bb476883e2d3b023f7b7d39d064d58ba5f1856869f75dca637c27c0303b731d082ff23a7e45ea2e3f9bcb8f3c4ce0c24332885d
        mode: '0644'
        owner: root
        group: root


    - name: get templ vm scriptoid
      copy:
        src: setup-debian-cloudinit.sh
        dest: /root/setup-debian-template.sh
        mode: '0755'
        owner: root
        group: root

    - name: run templ vm scriptoid
      shell:
        chdir: /root/
        cmd: /root/setup-debian-template.sh
