---
# NOTE: proxmox is only for containers, proxmox_kvm is only for VMs
#
# TODO: create ansible_pve user
#
# TODO: give following permissions to ansible_pve user:
#   path: /storage/local PVEDatastoreAdmin
#   path: /storage/local-zfs PVEDatastoreAdmin
#   path: /vms PVEVMAdmin
#
# TODO: automate download of container templates
#
# TODO: automate creation of template VMs
#
# TODO: automate addition of NFS using https://github.com/lae/ansible-role-proxmox#storage-management
#
# NOTE: good role for some of the above: https://github.com/lae/ansible-role-proxmox#user-and-acl-management

# Clone VM with only source VM name
#- proxmox_kvm:
#    api_host    : 192.168.70.1
#    api_user    : ansible_pve@pve
#    api_password: oomfie1234
#    clone       : deb-tmpl   # The VM source
#    name        : homeassistant  # The target VM name
#    node        : pve0
#    storage     : nfsprox
#    format      : raw
#    timeout     : 600  # The task can take a while, adjust accordingly

- hosts: proxie #pve0 is commented out
  become: True
  roles:
    - role: lae.proxmox

#- name: Create and Start LXC container(s)
#  hosts: pve1
#
#  tasks:
#  - name: Create test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      hostname: testdeb
#      ostemplate: local:vztmpl/debian-11-standard_11.3-1_amd64.tar.zst
#      cpus: 1
#      cpuunits: 500
#      memory: 128
#      disk: 'local-zfs:8'
#      netif: '{"net0":"name=eth0,gw=192.168.0.1,ip=192.168.25.100/24,bridge=vmbr0"}'
#      onboot: yes
#      unprivileged: yes
#      pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5jzKi37jm3517bqThbw+7LR/GXm3qC6Az5F+ZUa36vYM7Ygk2K5bWcFIL2YUCrkL5jfSsvoowONjCAxyuoyxtW4MJxnQLyq4u4yDsRC7YvBPAKZUYaHwnbkCfDs5a75dEFOoDxCA0DY2GrhqzBndaTcCfl0fZ4vN+9LcKOb1dSKiHeHvsh35YNtwntbL21meo+hiycUEgGwNe9/4kxKpdGTr7HvbeX2Fjm/UZBZIJKVcGop/3gCHXYnKH+OY5zc8cmt9Jg4CIwEqrSKeOX0bE8LSPRpVRXH4v8OcMaMei/HQejlH8NBwybEdJ4mhl8vHaFEjDbIWoOujmiRQF2263 angle@puddle'
#      state: present
#
#  - name: Start test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      state: started
#
#- name: Stop and Delete LXC container(s)
#  hosts: pve1
#
#  tasks:
#  - name: Stop test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      state: stopped
#
#  - name: Delete test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      state: absent
#
