---
# NOTE: proxmox is only for containers, proxmox_kvm is only for VMs
#
# TODO: create ansible_pve user
#
# TODO: give following permissions to ansible_pve user:
#   path: /storage/local PVEDatastoreAdmin
#   path: /storage/local-zfs PVEDatastoreAdmin
#   path: /vms PVEVMAdmin
#
# TODO: automate download of container templates
#
# TODO: automate creation of template VMs
#
# TODO: automate addition of NFS using https://github.com/lae/ansible-role-proxmox#storage-management
#
# NOTE: good role for some of the above: https://github.com/lae/ansible-role-proxmox#user-and-acl-management
#
# NOTE: removing VMs with proxmox_kvm seems to do nothing the first time but works the second time

- hosts: proxie
  become: True
  roles:
    - role: lae.proxmox

- name: Create and Start VM(s)
  hosts: pve1
  tasks:

#  - name: Remove test VMs
#    proxmox_kvm:
#      api_host    : 192.168.70.2
#      api_user    : root@pam
#      api_password: failfail
#      name        : "deb-test-{{ item }}"  # The target VM name
#      node        : pve1
#      state       : absent
#      timeout     : 400  # The task can take a while, adjust accordingly
#    with_sequence: start=1 end=5

  - name: Create test VM from debian 10 template
    proxmox_kvm:
      api_host    : 192.168.70.2
      api_user    : root@pam
      api_password: failfail
      clone       : debian-tmpl  # The VM source
      vmid        : 9001  # source VM id
      name        : "deb-test-{{ item }}"  # The target VM name
      node        : pve1
      storage     : local-zfs
      format      : raw
      timeout     : 300  # The task can take a while, adjust accordingly
    with_sequence: start=1 end=5

  - name: Start test VM 1
    proxmox_kvm:
      api_host    : 192.168.70.2
      api_user    : root@pam
      api_password: failfail
      name        : deb-test-1  # The target VM name
      node        : pve1
      state       : started
      timeout     : 300  # The task can take a while, adjust accordingly

  - name: Stop test VM 1
    proxmox_kvm:
      api_host    : 192.168.70.2
      api_user    : root@pam
      api_password: failfail
      name        : deb-test-1  # The target VM name
      node        : pve1
      state       : stopped
      force       : yes
      timeout     : 300  # The task can take a while, adjust accordingly


  - name: Create test VMs from debian 11 template
    proxmox_kvm:
      api_host    : 192.168.70.2
      api_user    : root@pam
      api_password: failfail
      clone       : debian-templ  # The VM source
      vmid        : 9002  # source VM id
      name        : deb-test-2  # The target VM name
      newid       : 302  # target VM id
      node        : pve1
      storage     : local-zfs
      format      : raw
      timeout     : 300  # The task can take a while, adjust accordingly

  - name: Start test VM 2
    proxmox_kvm:
      api_host    : 192.168.70.2
      api_user    : root@pam
      api_password: failfail
      name        : deb-test-2  # The target VM name
      node        : pve1
      state       : started
      timeout     : 300  # The task can take a while, adjust accordingly

  - name: Stop test VM 2
    proxmox_kvm:
      api_host    : 192.168.70.2
      api_user    : root@pam
      api_password: failfail
      name        : deb-test-2  # The target VM name
      node        : pve1
      state       : stopped
      force       : yes
      timeout     : 300  # The task can take a while, adjust accordingly

#  tasks:
#  - name: Create test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      hostname: testdeb
#      ostemplate: local:vztmpl/debian-11-standard_11.3-1_amd64.tar.zst
#      cpus: 1
#      cpuunits: 500
#      memory: 128
#      disk: 'local-zfs:8'
#      netif: '{"net0":"name=eth0,gw=192.168.0.1,ip=192.168.25.100/24,bridge=vmbr0"}'
#      onboot: yes
#      unprivileged: yes
#      pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5jzKi37jm3517bqThbw+7LR/GXm3qC6Az5F+ZUa36vYM7Ygk2K5bWcFIL2YUCrkL5jfSsvoowONjCAxyuoyxtW4MJxnQLyq4u4yDsRC7YvBPAKZUYaHwnbkCfDs5a75dEFOoDxCA0DY2GrhqzBndaTcCfl0fZ4vN+9LcKOb1dSKiHeHvsh35YNtwntbL21meo+hiycUEgGwNe9/4kxKpdGTr7HvbeX2Fjm/UZBZIJKVcGop/3gCHXYnKH+OY5zc8cmt9Jg4CIwEqrSKeOX0bE8LSPRpVRXH4v8OcMaMei/HQejlH8NBwybEdJ4mhl8vHaFEjDbIWoOujmiRQF2263 angle@puddle'
#      state: present
#
#  - name: Start test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      state: started
#
#- name: Stop and Delete LXC container(s)
#  hosts: pve1
#
#  tasks:
#  - name: Stop test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      state: stopped
#
#  - name: Delete test container
#    proxmox:
#      api_host: 192.168.70.2
#      api_user: ansible@pve
#      api_password: oomfie1234
#      node: pve1
#      vmid: 100
#      state: absent
#
