---
- name: Restart redis
  ansible.builtin.service:
    name: "{{ redis_service_name }}"
    state: restarted
  when: redis_as_service

- name: Restart sentinel
  ansible.builtin.service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted
  when: redis_as_service
