---
- name: Download and extract stable NetBox release
  ansible.builtin.unarchive:
    src: "{{ netbox_stable_uri }}"
    dest: "{{ netbox_releases_path }}"
    creates: "{{ netbox_stable_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    remote_src: true

- name: Symlink stable release to current NetBox directory
  ansible.builtin.file:
    src: "{{ netbox_stable_path }}"
    dest: "{{ netbox_current_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: link
  notify:
    - Reload netbox.service
