---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-base
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/cluster01/core/longhorn/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
