---

- name: install docker
  hosts:
    - dock
  become: true
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - docker_user
    docker_install_compose: true
    docker_compose_version: "1.26.2"
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
    - name: create to-be home dir for dockboi
      file:
        path: /opt/user
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: create to-be home dir for dockboi
      file:
        path: /opt/user/docker
        state: directory
        mode: "0755"
        owner: docker_user
        group: docker_user

    - name: add non-root boi
      user:
        name: docker_user
        uid: 1040
        home: /opt/user/docker
        shell: /bin/bash

    - name: move docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /opt/user/docker/docker-compose.yml
        mode: "0644"
        owner: docker_user
        group: docker_user
        backup: yes

    - name: move .env for docker-compose
      copy:
        src: dotenv-compose
        dest: /opt/user/docker/.env
        mode: "0644"
        owner: docker_user
        group: docker_user
        backup: yes

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
