---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metabase
  namespace: &ns default
spec:
  chart:
    spec:
      chart: minecraft
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft-charts
      version: 4.26.3
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  #TODO: values
