apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
data:
  config.json: |-
    [
      {
        "clusterID": "d2f1d416-597d-11eb-a329-d027881dd7f8",
        "monitors": [
          "192.168.10.1:6789",
        ]
      }
    ]
