---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitlab-agent
  namespace: &ns default
spec:
  interval: 10m
  path: ./fluxcd/homecluster/apps/default/gitlab-agent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  timeout: 5m
  wait: true
