---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Storage
  - ./openebs/kustomization-fluxCRD.yaml
  # Network
  - ./metallb/kustomization-fluxCRD.yaml
  - ./ingress-nginx/kustomization-fluxCRD.yaml
  - ./cert-manager/kustomization-fluxCRD.yaml
  #- ./external-dns/kustomization-fluxCRD.yaml
