---
dependencies: []

galaxy_info:
  role_name: postgresql
  author: geerlingguy
  description: PostgreSQL server for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Fedora
      versions:
        - 34
        - 35
        - 36
        - 37
        - 38
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - database
    - postgresql
    - postgres
    - rdbms
