apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: gifinator
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/var/lib/redis"
          name: gifinator-redis-data
      volumes:
        - name: gifinator-redis-data
          persistentVolumeClaim:
            claimName: gifinator-redis-data-pvc
