---
- name: Ensure MySQL packages are installed.
  ansible.builtin.dnf:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
