---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app podinfo
  namespace: &ns default
spec:
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: 6.7.0
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hosts:
      - host: podinfo.inherently.xyz
        paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
        - hosts:
            - podinfo.inherently.xyz
          secretName: podinfo-tls
    ui:
      color: '#440044'
      message: inherent podinfo
