---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 4.1.3
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: openebs
  targetNamespace: openebs
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    iopenebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: true
    mayastor:
      crds:
        enabled: false
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        clusterDomain: cluster.local
      localpv-provisioner:
        enabled: false
