---

- name: Install gnupg
  ansible.builtin.apt:
    name: gnupg
    update_cache: true
    state: present
    cache_valid_time: 100
  when: ansible_distribution == 'Debian'
  become: true
  tags:
    - deluge

- name: Add ubuntu source
  ansible.builtin.apt_repository:
    repo: deb [trusted=yes] http://ppa.launchpad.net/deluge-team/stable/ubuntu/ xenial main
    state: present
  when: ansible_distribution == 'Debian'
  become: true
  tags:
    - deluge

- name: Add ubuntu apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: C5E6A5ED249AD24C
    state: present
  become: true
  when: ansible_distribution == 'Debian'
  tags:
    - deluge

- name: Install Deluge Daemon
  ansible.builtin.apt:
    name: ['deluged', 'deluge-console']
    update_cache: true
    state: present
    cache_valid_time: 3600
  become: true
  tags:
    - deluge

- name: Install Deluge Web
  ansible.builtin.apt:
    name: deluge-web
    update_cache: true
    state: present
    cache_valid_time: 3600
  become: true
  when: deluge_web
  tags:
    - deluge
    - deluge_web
