---
# handlers file for ansible-role-proxmox
- name: Restart pvedaemon
  ansible.builtin.service:
    name: pvedaemon
    state: restarted

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Reload ssh server configuration
  ansible.builtin.systemd:
    name: ssh.service
    state: reloaded

- name: Restart watchdog-mux
  ansible.builtin.service:
    name: watchdog-mux
    state: restarted

- name: Restart zfs-zed
  ansible.builtin.service:
    name: zfs-zed
    state: restarted

- name: Restart ceph
  # Needs to use the systemd module directly to be able to
  # reload the systemd daemon
  ansible.builtin.systemd:
    name: ceph.service
    state: restarted
    daemon_reload: true
