---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.14.5
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    extraArgs:
    - --pihole-password=failfail
    - --pihole-server=https://pihole.home.inherently.xyz
    policy: upsert-only
    provider:
      name: pihole
    registry: noop
