apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: drone
  labels:
    app: postgres
data:
  POSTGRES_DB: dronecidb
  POSTGRES_USER: droneciuser
  POSTGRES_PASSWORD: DRONEs-CIrcling-4b0v3

