apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-drone-pvc
  namespace: drone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 15Gi
