apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-drone-data-pvc
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 15Gi
