apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
spec:
  storageClassName: ""
  claimRef:
    name: todo-data-pvc
    namespace: todo
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.50.100
    path: "/mnt/tank-z1/k8/todo"
  mountOptions:
    - nfsvers=4
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: todo-pv
#spec:
#  storageClassName: local-path
#  claimRef:
#    name: todo-local-data-pvc
#    namespace: todo
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: /var/lib/rancher/k3s/storage/todo
#    type: DirectoryOrCreate
#  volumeMode: Filesystem
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - k3s-single
