apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo
  namespace: todo
spec:
  rules:
  - host: todo.kates.test
    http:
      paths:
      - path: /
        backend:
          serviceName: todo-svc
          servicePort: 8080
