apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
