apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: gitlab-runner
stringData:
    token: ENC[AES256_GCM,data:EmH7C6B+4VctifSEfWr1EtFykYrk1tGdaA==,iv:92u36b5KI2fiUr11giy3QVGElRWN7t9CtAmIXuE5NC4=,tag:eI6CGVY7IHK5kMH/CYkL2A==,type:str]
sops:
    age:
        - recipient: age1aa9sefsfad7w4hg7xqeg2pr2875vqhtsz228jz0svcssgcf99a9s8ma3nj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWWZxQ0lhTFVwR2hSUVly
            TmxVejVkcEhCUEowMURHelJhLzRCT1BaemlNClFra3VtblhDQ3JiUDB3K3M4QXJG
            alJIZ2x4Rk5YdllFalVHU2lLRVNndUkKLS0tIHBQWmh6MmhHRGNMMmYxYU9scTJU
            VUk5MytTOW04azZVSVN4MW9zTy9zOTAKE6rMw0DRzJ7wglvXb0jz3j+b0MMFHfX5
            Xzlmy4LGeDAX4HNhfOw7/nOZmvq+d10dLcjyBCPa0WdwBSM1OjS+xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T16:28:19Z"
    mac: ENC[AES256_GCM,data:saY33WGGxLKjLpgw/P1TQGFJZRgDqN4LMcgG6zYsHleBaiyB6BuEWwVwyAEPPjvNarW09MfB4dvZUrRUfpi4ixp3n4KbqFxLUiFCoaQkdzaoQ8vYP0w0EJbJ8i8K1QYSZlsthQIcqpULHxZ201P6BqJWRGRkR08ZGbPPYQAwyxg=,iv:q3AKrNigmM78HmzbqQ/YUvfOuV+XwCyEXrpBub7FanE=,tag:GI1rk1ZukjGXYu0xrUTksg==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.10.1
