---
dependencies: []

galaxy_info:
  role_name: deluge
  author: Steven Marks
  description: Deluge2 install & configuration
  company: "Total Debug"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.4"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - deluge
    - deluge2
    - torrent
