---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lister
  namespace: flux-system
spec:
  chart:
    spec:
      chart: lister
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lister
      version: 0.2.2
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: lister
