---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ingress-nginx
  namespace: &ns network
spec:
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.12.1
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: *app
  targetNamespace: *ns
  values:
    controller:
      ingressClassResource:
        default: true
        enabled: true
      maxUnavailable: 1
      publishService:
        enabled: true
      replicaCount: 1
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "nginx.home.inherently.xyz"
        enabled: true
        external:
          enabled: true
        loadBalancerIP: 10.0.50.150
        type: LoadBalancer
      terminationGracePeriodSeconds: 300
      updateStrategy:
        type: RollingUpdate
      watchIngressWithoutClass: true
      extraArgs:
        default-ssl-certificate: network/nginx-tls
