ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

	# vagrant settings
	config.vm.box = "centos/7"

	#config.vm.box_check_update = false

	config.ssh.insert_key = false

	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.provider :libvirt do |v|
		v.memory = 1024
		v.cpus = 2
	end


	# app server 1
	config.vm.define "app1" do |app|
		app.vm.hostname = "orc-app1.test"
		app.vm.network "private_network", ip: "192.168.121.13"
	end

	# app server 2
	config.vm.define "app2" do |app|
		app.vm.hostname = "orc-app2.test"
		app.vm.network "private_network", ip: "192.168.121.14"
	end

	# db server
	config.vm.define "db" do |db|
		db.vm.hostname = "orc-db.test"
		db.vm.network "private_network", ip: "192.168.121.15"
	end

end

# vim: set ft=ruby :
