name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message:  'Hello @${{ github.actor }}, thank you for submitting a PR! We will review your changes and respond as soon as possible.'
        issue-message: |
          Hello @${{ github.actor }}, thank you for your interest in our work!
          If this is a bug report, please provide your configuration and any screenshots that would assist troubleshooting, otherwise we can not help you.
