---
galaxy_info:
  author: elnappo <elnappo@nerdpol.io>
  description: Install apt-cacher-ng
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - packaging
    - apt

dependencies: []
