apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
spec:
  rules:
  - host: gitea.kates.test
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea-service
          servicePort: 3000
