apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 22Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-etc-pvc
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 3Gi
