---
- name: Install apt-cacher-ng
  hosts: aptcache
  become: true
  roles:
    - role: elnappo.apt_cacher_ng
      vars:
        apt_cacher_ng_setup_ufw: false

- name: Configure apt-cacher-ng clients
  hosts: all:!proxmox_servers
  become: true
  tasks:
    - name: Configure debian hosts to use apt-cacher-ng
      ansible.builtin.template:
        src: templates/apt_proxy.conf.j2
        dest: /etc/apt/apt.conf.d/01proxy
        owner: root
        group: root
        mode: "0644"
      when: ansible_os_family == "Debian" and apt_proxy is defined
