---
- name: Install and configure FOG
  hosts: fog
  become: true

  tasks:
    - name: Download release tarball
      ansible.builtin.get_url:
        url: https://github.com/FOGProject/fogproject/archive/1.5.10.tar.gz
        dest: /opt/fog-1_5_10.tar.gz
        mode: '0644'
        owner: root
        group: root

    - name: Unarchive fog tarball
      ansible.builtin.unarchive:
        src: /opt/fog-1_5_10.tar.gz
        dest: /opt/
        remote_src: true
        creates: /opt/fogproject-1.5.10/bin/installfog.sh

    - name: Run install script
      ansible.builtin.command:
        chdir: /opt/fogproject-1.5.10/bin/
        cmd: ./installfog.sh --autoaccept
      register: fog_install_output
      changed_when: "'Setup complete' in fog_install_output.stdout"
...
