---
- name: Get SSL certs for grafana
  hosts: grafana_servers
  become: true
  tasks:
    - name: Get Cloudflare LE cert
      ansible.builtin.import_role:
        name: cloudflare_le_cert
      vars:
        cloudflare_cert_domains:
          - grafana01.home.inherently.xyz
          - grafana.home.inherently.xyz
        cloudflare_cert_file_dest: /etc/ssl/grafana.home.inherently.xyz.crt
        cloudflare_key_file_dest: /etc/ssl/grafana.home.inherently.xyz.key

- name: Deploy Grafana
  hosts: grafana
  become: true
  roles:
    - role: grafana.grafana.grafana
