---
- name: Deploy Grafana
  hosts: grafana
  become: true

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      loop:
        - apt-transport-https
        - software-properties-common

    - name: Add Grafana debian repo signed by gpg key
      ansible.builtin.deb822_repository:
        name: grafana
        types: [deb]
        signed_by: https://apt.grafana.com/gpg.key
        uris: https://apt.grafana.com
        suites: stable
        components: [main]
        enabled: true
        state: present

    - name: Install grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: true
        state: present

    - name: Start and enable grafana service
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
        state: started

    - name: Wait for grafana to start
      ansible.builtin.wait_for:
        port: 3000
        delay: 5
        timeout: 60
...
