---
- name: Install kubernetes deps
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - nfs-common
          - nfs4-acl-tools

- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s.orchestration.prereq
    - role: k3s.orchestration.airgap
    - role: k3s.orchestration.raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s.orchestration.k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s.orchestration.k3s_agent
