---
- name: Cluster prep
  hosts: k3s_cluster_1
  gather_facts: true
  become: true
  roles:
    - role: k3s_roles/prereq
    - role: k3s_roles/airgap
    - role: k3s_roles/raspberrypi

- name: Setup K3S server
  hosts: k3s_server_1
  become: true
  roles:
    - role: k3s_roles/k3s_server

- name: Setup K3S agent
  hosts: k3s_agent_1
  become: true
  roles:
    - role: k3s_roles/k3s_agent
