---
# Servers should be restarted sequientally to avoid etcd learner issues
# Agents have no such limitation
- name: Upgrade K3s Servers
  hosts: k3s_server_1
  become: true
  serial: 1
  roles:
    - role: k3s_roles/k3s_upgrade

- name: Upgrade K3s Agents
  hosts: k3s_agent_1
  become: true
  roles:
    - role: k3s_roles/k3s_upgrade
