---
- name: Get SSL certs for keycloak
  hosts: keycloak_servers
  become: true
  tasks:
    - name: Get Cloudflare LE cert
      ansible.builtin.import_role:
        name: cloudflare_le_cert
      vars:
        cloudflare_cert_domains:
          - keycloak01.home.inherently.xyz
          - keycloak.home.inherently.xyz
        cloudflare_cert_file_dest: /etc/ssl/keycloak.home.inherently.xyz.crt.pem
        cloudflare_key_file_dest: /etc/ssl/keycloak.home.inherently.xyz.key

- name: Install keycloak
  hosts: keycloak_servers
  become: true
  roles:
    - role: middleware_automation.keycloak.keycloak_quarkus
