---
- name: Install and configure LibreNMS
  hosts: librenms
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - wget
          - acl
          - curl
          - fping
          - git
          - graphviz
          - imagemagick
          - mariadb-client
          - mariadb-server
          - mtr-tiny
          - nginx-full
          - nmap
          - php8.2-cli
          - php8.2-curl
          - php8.2-fpm
          - php8.2-gd
          - php8.2-gmp
          - php8.2-mbstring
          - php8.2-mysql
          - php8.2-snmp
          - php8.2-xml
          - php8.2-zip
          - python3-dotenv
          - python3-pymysql
          - python3-redis
          - python3-setuptools
          - python3-systemd
          - python3-pip
          - rrdtool
          - snmp
          - snmpd
          - unzip
          - whois
          - composer

    - name: Clone librenms repository
      ansible.builtin.git:
        repo: https://github.com/librenms/librenms.git
        dest: /opt/librenms
        version: 24.1.0
        update: false
        single_branch: true

    - name: Change directory permissions
      ansible.builtin.file:
        path: /opt/librenms
        owner: librenms
        group: librenms
        mode: '771'
        recurse: true
        state: directory

    - name: Set ACL
      ansible.posix.acl:
        path: "{{ item }}"
        etype: group
        permissions: rwx
        default: true
        recurse: true
        state: present
      loop:
        - /opt/librenms/rrd
        - /opt/librenms/logs
        - /opt/librenms/bootstrap/cache/
        - /opt/librenms/storage/

    - name: Add librenms user
      ansible.builtin.user:
        name: librenms
        system: true
        shell: /bin/bash
        home: /opt/librenms
        state: present

    - name: Set PHP timezone
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^date.timezone = '
        insertafter: '^;date.timezone = '
        line: "date.timezone = {{ ntp_timezone }}"
      loop:
        - /etc/php/8.2/fpm/php.ini
        - /etc/php/8.2/cli/php.ini
...
