---
- name: Install and configure MySQL
  hosts: mysql
  become: true
  tasks:
    - name: Initial mysql install and setup
      ansible.builtin.import_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_password_update: false # set to true if root password here is changed
        mysql_root_username: root
        mysql_root_password: "*2304CA907AD20C629F898FCE11C167F21663318A"
        mysql_bind_address: 0.0.0.0
        mysql_databases:
          - name: testmysqldb
        mysql_users:
          - name: testmysqluser
            host: "%"
            password: "*CB03FF1A1F88F88B238BBC3AC17C11AC32E498E4"
            priv: testmysqldb.*:ALL

    - name: Ensure mysql SSL dir exists
      ansible.builtin.file:
        path: /etc/mysql/ssl
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: Get Cloudflare LE cert
      ansible.builtin.import_role:
        name: cloudflare_le_cert
      vars:
        cloudflare_cert_domains:
          - mysql01.home.inherently.xyz
          - mysql.home.inherently.xyz
        cloudflare_cert_file_dest: /etc/mysql/ssl/server-cert.pem
        cloudflare_key_file_dest: /etc/mysql/ssl/server-key.pem

    - name: Set mysql SSL cert file
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: "^ssl-cert "
        insertafter: "^#ssl-cert "
        line: ssl-cert=/etc/mysql/ssl/server-cert.pem

    - name: Set mysql SSL private key file
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: "^ssl-key "
        insertafter: "^#ssl-key "
        line: ssl-key=/etc/mysql/ssl/server-key.pem
