---
- name: Install and configure MySQL
  hosts: mysql
  become: true
  tasks:
    - name: Initial mysql install and setup
      ansible.builtin.import_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_password_update: true
        mysql_root_password: mysqladmin123
        # TODO: Check if the following works
        # mysql_databases:
        #   - name: testmysqldb
        # mysql_users:
        #   - name: "{{ mysql_root_user }}"
        #     password: "{{ mysql_root_password }}"
        #   - name: testmysqluser
        #     host: "%"
        #     password: testmysqluserpassword123
        #     priv: "testmysqldb.*:ALL"

    - name: Install CloudFlare certbot plugin
      ansible.builtin.apt:
        name: python3-certbot-dns-cloudflare
        update_cache: true
        state: present

    - name: Create cloudflare credentials file
      ansible.builtin.template:
        src: cloudflare.ini.j2
        dest: /etc/ssl/cloudflare.ini
        mode: "0600"
        owner: root
        group: root

    - name: Get LetsEncrypt TLS certificates
      ansible.builtin.import_role:
        name: geerlingguy.certbot
      vars:
        certbot_install_method: package
        certbot_create_if_missing: true
        certbot_create_method: standalone
        certbot_admin_email: pepitsizous@zoho.com
        certbot_certs:
          - domains:
              - mysql01.home.inherently.xyz
        certbot_create_command: "{{ certbot_script }} certonly --preferred-challenges dns --dns-cloudflare --dns-cloudflare-credentials /etc/ssl/cloudflare.ini --noninteractive
          --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
        certbot_create_standalone_stop_services: []
        certbot_auto_renew_user: root
