---
- name: Install and configure Observium
  hosts: observium
  become: true
  tasks:
    - name: Copy fully automatic observium install script
      ansible.builtin.copy:
        src: files/2024-02-17_observium_fullauto_installscript.sh
        dest: /root/observium_fullauto_installscript.sh
        mode: "0777"
        owner: root
        group: root

    - name: Run observium install script
      ansible.builtin.command:
        chdir: /root/
        cmd: ./observium_fullauto_installscript.sh
      register: observium_install_output
      changed_when: "'Installation finished' in observium_install_output.stdout"
