---
- name: Configure pihole
  hosts: piholes
  become: true

  tasks:
    - name: Install unbound
      ansible.builtin.apt:
        name: unbound
        update_cache: true
        state: present

    - name: Download root hints
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/lib/unbound/root.hints
        mode: '0644'
        owner: root
        group: root

    - name: Copy dnsmasq edns-related config to pihole
      ansible.builtin.copy:
        src: 99-edns.conf
        dest: /etc/dnsmasq.d/99-edns.conf
        mode: '0644'
        owner: root
        group: root

    - name: Restart unbound service
      ansible.builtin.service:
        name: unbound
        enabled: true
        state: restarted
...
