---
- name: Configure pihole
  hosts: pihole
  become: true

  tasks:
    - name: Create a directory for the install script
      ansible.builtin.file:
        path: /opt/pihole-install
        state: directory
        mode: '0755'

    - name: Download PiHole install script
      ansible.builtin.get_url:
        url: https://install.pi-hole.net
        dest: /opt/pihole-install/basic-install.sh
        mode: '0755'
        owner: root
        group: root

    - name: Create a directory for pihole
      ansible.builtin.file:
        path: /etc/pihole
        state: directory
        mode: '0755'

    - name: Copy over setupVars.conf
      ansible.builtin.copy:
        src: setupVars.conf
        dest: /etc/pihole/setupVars.conf
        mode: '0644'
        owner: root
        group: root

    - name: Run pihole install script
      ansible.builtin.command:
        chdir: /opt/pihole-install/
        cmd: ./basic-install.sh --unattended
      register: pihole_install_output
      changed_when: "'pihole' in pihole_install_output.stdout"

    - name: Add redirect from webroot to admin
      ansible.builtin.lineinfile:
        path: /etc/lighttpd/lighttpd.conf
        line: url.redirect = ("^/$" => "/admin" )
        insertafter: EOF

    - name: Restart lighttpd service
      ansible.builtin.service:
        name: lighttpd
        enabled: true
        state: restarted

    - name: Install unbound
      ansible.builtin.apt:
        name: unbound
        update_cache: true
        state: present

    - name: Download root hints
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/lib/unbound/root.hints
        mode: '0644'
        owner: root
        group: root

    - name: Copy dnsmasq edns-related config to pihole
      ansible.builtin.copy:
        src: 99-edns.conf
        dest: /etc/dnsmasq.d/99-edns.conf
        mode: '0644'
        owner: root
        group: root

    - name: Restart unbound service
      ansible.builtin.service:
        name: unbound
        enabled: true
        state: restarted
...
