---
- name: Install and configure PostgreSQL
  hosts: postgres
  become: true
  tasks:
    # import_role tasks parsed at the beginning, include_role tasks parsed when they're going to run
    # source: https://www.ansiblejunky.com/blog/ansible-101-include-vs-import/
    - name: Initial postgres install and setup
      ansible.builtin.import_role:
        name: geerlingguy.postgresql

    - name: Get Cloudflare LE cert
      ansible.builtin.import_role:
        name: cloudflare_le_cert
      vars:
        cloudflare_cert_domains:
          - postgres01.home.inherently.xyz
          - postgres.home.inherently.xyz
        cloudflare_cert_file_dest: /etc/postgresql/15/main/fullchain.pem
        cloudflare_key_file_dest: /etc/postgresql/15/main/privkey.pem

    - name: Set SSL to on
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: ^ssl =
        line: ssl = on

    - name: Set SSL cert file
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^ssl_cert_file "
        insertafter: "^#ssl_cert_file "
        line: ssl_cert_file = '/etc/postgresql/15/main/fullchain.pem'

    - name: Set SSL private key file
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^ssl_key_file "
        insertafter: "^#ssl_key_file "
        line: ssl_key_file = '/etc/postgresql/15/main/privkey.pem'

    # Command to test SSL connection
    # PGSSLMODE=verify-full PGSSLROOTCERT=system psql -h postgres01.home.inherently.xyz -U testuser -d testdb
