---
- name: Install and configure PowerDNS Authoritative Server
  hosts: powerdns
  become: true
  roles:
    - name: Install PowerDNS Authoritative Server
      role: PowerDNS.pdns
      pdns_install_repo: "{{ pdns_auth_powerdns_repo_48 }}"
    - name: Install PowerDNS Recursor
      role: PowerDNS.pdns_recursor
      pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_50 }}"
