---
# NOTE: to troubleshoot, export CI="pleasegivelogs"
- name: Install and configure Prometheus stack
  hosts: prometheus_servers
  become: true
  tasks:
    - name: Get Cloudflare LE cert
      ansible.builtin.import_role:
        name: cloudflare_le_cert
      vars:
        cloudflare_cert_domains:
          - prometheus01.home.inherently.xyz
          - prometheus.home.inherently.xyz
        cloudflare_cert_file_dest: /etc/ssl/prometheus01.home.inherently.xyz.crt
        cloudflare_key_file_dest: /etc/ssl/prometheus01.home.inherently.xyz.key

    - name: Install and configure Prometheus
      ansible.builtin.import_role:
        name: prometheus.prometheus.prometheus

    - name: Install and configure blackbox_exporter
      ansible.builtin.import_role:
        name: prometheus.prometheus.blackbox_exporter

- name: Install and configure additional Prometheus exporters
  hosts: all:!desktops
  become: true
  tasks:
    - name: Install and configure Node Exporter
      ansible.builtin.import_role:
        name: prometheus.prometheus.node_exporter
