---
# NOTE: to troubleshoot, export CI="pleasegivelogs"
- name: Install and configure Prometheus stack
  hosts: prometheus
  become: true
  roles:
    - name: Install and configure Prometheus
      role: prometheus.prometheus.prometheus
      prometheus_config_flags_extra:
        web.enable-admin-api:
      prometheus_targets:
        node:
          - targets: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('regex_replace', '$', ':9100') | list }}"
            labels:
              env: homelab
    - name: Install and configure blackbox_exporter
      role: prometheus.prometheus.blackbox_exporter
    - name: Install and configure Alertmanager
      role: prometheus.prometheus.alertmanager
      vars:
        alertmanager_receivers:
          - name: pushoverreceiver
            pushover_configs:
              - user_key: uwniin3jk1963uw7w1nmmhpji9tss9
                token: a31grho4qvd69bvn2k6mhhxaacbv3t
        alertmanager_route:
          receiver: pushoverreceiver

- name: Install and configure additional Prometheus exporters
  hosts: all:!gitlab_servers:!desktops
  become: true
  roles:
    - name: Install and configure Node Exporter
      role: prometheus.prometheus.node_exporter
