---
- name: Configure NTP on proxmox
  hosts: proxmox_servers
  become: true
  tasks:
    - name: Install keepalived
      ansible.builtin.apt:
        update_cache: true
        name:
          - keepalived

    - name: Copy keepalived configuration
      ansible.builtin.template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"

    - name: Restart keepalived
      ansible.builtin.systemd_service:
        name: keepalived
        enabled: true
        state: restarted

    - name: Configure NTP on proxmox
      hosts: proxmox_servers
      become: true
      roles:
        - role: geerlingguy.ntp

    - name: Set up proxmox cluster
      hosts: proxmox_servers
      become: true
      roles:
        - role: lae.proxmox

    - name: Proxmox post-config
      hosts: proxmox_servers
      become: true
      tasks:
        - name: Install useful packages
          ansible.builtin.apt:
            update_cache: true
            name:
              - vim
              - tmux
              - htop
              - python3
              - python3-apt
              - python3-guestfs
              - python3-proxmoxer
              - python-is-python3
              - nfs-common
              - nfs4-acl-tools
              - libguestfs-tools
            state: present

#     - name: Download Debian 12 genericcloud qcow2 image
#       ansible.builtin.get_url:
#         url: https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-amd64-20240717-1811.qcow2
#         dest: /tmp/debian-12-amd64.qcow2
#         checksum: sha512:0f0075d53749dba4c9825e606899360626bb20ac6bab3dbdeff40041b051d203eb1a56e68d377c9fac0187faa0aea77fd543ef4a883fff2304eac252cce01b44
#         mode: "0644"
#         owner: root
#         group: root
# 
#     - name: Add qemu-guest-agent to Debian 12 image
#       vkhitrin.libguestfs.guestfs_package:
#         image: /tmp/debian-12-amd64.qcow2
#         name: qemu-guest-agent
#         state: present
# 
#     - name: Remove unattended-upgrades from Debian 12
#       vkhitrin.libguestfs.guestfs_package:
#         image: /tmp/debian-12-amd64.qcow2
#         name: unattended-upgrades
#         state: absent
# 
#     - name: Copy /etc/network/interfaces config
#       ansible.builtin.copy:
#         src: debinterfaces
#         dest: /tmp/debinterfaces
#         owner: root
#         group: root
#         mode: "0644"
# 
#     - name: Change network interfaces config for Debian 12
#       vkhitrin.libguestfs.guestfs_copy_in:
#         image: /tmp/debian-12-amd64.qcow2
#         src: /tmp/debinterfaces
#         dest: /etc/network/interfaces
# 
#     - name: Create Debian 12 virtual machine
#       community.general.proxmox_kvm:
#         validate_certs: false # TODO: disable after figuring out LE certs
#         api_user: root@pam
#         api_password: failfail
#         api_host: "{{ ansible_host }}"
#         node: "{{ inventory_hostname }}"
#         vmid: "{{ template_vmid2 }}"
#         name: deb12-tmpl
#         description: debian 12 template
#         acpi: true
#         cpu: cputype=SandyBridge
#         cores: 1
#         sockets: 1
#         memory: 1024
#         numa_enabled: true
#         ostype: l26
#         boot: c
#         bootdisk: virtio0
#         scsihw: virtio-scsi-pci
#         ide:
#           ide2: local-lvm:cloudinit,format=raw
#         net:
#           net0: virtio,bridge=vmbr0
#         serial:
#           serial0: socket
#         vga: qxl
#         agent: enabled=1,fstrim_cloned_disks=1
#         hotplug: disk,network,usb,memory,cpu
#         tags: [debian, bookworm, debian12, template]
#         state: present
# 
#     - name: Add root disk imported from qcow2 image to Debian 12 virtual machine
#       community.general.proxmox_disk:
#         validate_certs: false # TODO: disable after figuring out LE certs
#         api_user: root@pam
#         api_password: failfail
#         api_host: "{{ ansible_host }}"
#         vmid: "{{ template_vmid2 }}"
#         name: deb12-tmpl
#         disk: virtio0
#         storage: local-lvm
#         import_from: /tmp/debian-12-amd64.qcow2
#         state: present
# 
#     - name: Convert Debian 12 virtual machine to template
#       community.general.proxmox_kvm:
#         validate_certs: false # TODO: disable after figuring out LE certs
#         api_user: root@pam
#         api_password: failfail
#         api_host: "{{ ansible_host }}"
#         node: "{{ inventory_hostname }}"
#         vmid: "{{ template_vmid2 }}"
#         name: deb12-tmpl
#         state: template
