---
- name: Configure NTP on proxmox
  hosts: proxie
  become: True
  roles:
    - role: geerlingguy.ntp

- name: Proxmox pre-config
  hosts: proxie
  become: true
  tasks:
    - name: Remove enterprise repo
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Install useful packages
      apt:
        name:
          - vim
          - tmux
          - htop
          - python3
          - python3-apt
          - python3-guestfs
          - python3-proxmoxer
          - python-is-python3
          - nfs-common
          - nfs4-acl-tools
          - libguestfs-tools
        state: present

- name: Set up proxmox cluster
  hosts: proxie
  become: true
  roles:
    - role: lae.proxmox

- name: Proxmox post-config
  hosts: proxie
  become: true
  tasks:
    - name: get deb-11 could image
      get_url:
        url: https://cloud.debian.org/images/cloud/bullseye/20240104-1616/debian-11-genericcloud-amd64-20240104-1616.qcow2
        dest: /tmp/debian-11-amd64.qcow2
        checksum: sha512:01f1a9aa92f6257936193359642d7ff780ad3c721f4b731ed0a04684f015db66d7919a72b2b2a272a7dd3cf0e4e0314694c00684c333552a01bd149a535f2a09
        mode: '0644'
        owner: root
        group: root

    - name: Copy /etc/network/interfaces virtual machine configuration
      copy:
        src: debinterfaces
        dest: /tmp/debinterfaces
        owner: root
        group: root
        mode: '0644'

    - name: Add qemu-guest-agent to the debian image
      vkhitrin.libguestfs.guestfs_package:
        image: /tmp/debian-11-amd64.qcow2
        name: qemu-guest-agent
        state: present

    - name: Remove unattended-upgrades from the debian image
      vkhitrin.libguestfs.guestfs_package:
        image: /tmp/debian-11-amd64.qcow2
        name: unattended-upgrades
        state: absent

    - name: Upload a file and rename it on guest disk image
      vkhitrin.libguestfs.guestfs_copy_in:
        image: /tmp/debian-11-amd64.qcow2
        src: '/tmp/debinterfaces'
        dest: '/etc/network/interfaces'

    - name: Create Debian 11 virtual machine
      community.general.proxmox_kvm:
        validate_certs: false #TODO: disable after figuring out LE certs
        api_user: root@pam
        api_password: failfail
        api_host: "{{ ansible_host }}"
        node: "{{ inventory_hostname }}"
        vmid: "{{ template_vmid }}"
        name: deb11-tmpl
        description: debian 11 template
...
