---

- name: Configure NTP on proxmox
  hosts: proxmox_servers
  become: true
  tasks:
    - name: Install systemd-timesyncd
      ansible.builtin.apt:
        update_cache: true
        name:
          - systemd-timesyncd

- name: Add syslog daemon to proxmox
  hosts: proxmox_servers
  become: true
  tasks:
    - name: Install rsyslog
      ansible.builtin.apt:
        update_cache: true
        name:
          - rsyslog

- name: Configure HAProxy on proxmox hosts
  hosts: proxmox_servers
  become: true
  tasks:
    - name: Install keepalived
      ansible.builtin.apt:
        update_cache: true
        name:
          - keepalived
      register: keepalived_new

    - name: Stop keepalived
      ansible.builtin.systemd_service:
        name: keepalived
        enabled: true
        state: stopped
      when: keepalived_new.changed

    - name: Copy keepalived configuration
      ansible.builtin.template:
        src: proxmox-keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      register: keepalived_config

    - name: Restart keepalived
      ansible.builtin.systemd_service:
        name: keepalived
        enabled: true
        state: restarted
      when: keepalived_config.changed

    - name: Ensure keepalived is started
      ansible.builtin.systemd_service:
        name: keepalived
        enabled: true
        state: started

    - name: Install CloudFlare certbot plugin
      ansible.builtin.apt:
        name: python3-certbot-dns-cloudflare
        update_cache: true
        state: present

    - name: Create cloudflare credentials file
      ansible.builtin.template:
        src: cloudflare.ini.j2
        dest: /etc/ssl/cloudflare.ini
        mode: "0600"
        owner: root
        group: root

    - name: Get LetsEncrypt TLS certificates
      ansible.builtin.import_role:
        name: geerlingguy.certbot
      vars:
        certbot_install_method: package
        certbot_create_if_missing: true
        certbot_create_method: standalone
        certbot_admin_email: pepitsizous@zoho.com
        certbot_certs:
          - domains:
              - pve.home.inherently.xyz
        certbot_create_command: "{{ certbot_script }} certonly --preferred-challenges dns --dns-cloudflare --dns-cloudflare-credentials /etc/ssl/cloudflare.ini --noninteractive --agree-tos --email
          {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
        certbot_create_standalone_stop_services: []
        certbot_auto_renew_user: root

    - name: Delete LE README before creating combined SSL file
      ansible.builtin.file:
        path: /etc/letsencrypt/live/pve.home.inherently.xyz/README
        state: absent

    - name: Create combined SSL file
      ansible.builtin.assemble:
        src: /etc/letsencrypt/live/pve.home.inherently.xyz
        dest: /etc/letsencrypt/live/combined.pem

    - name: Install haproxy
      ansible.builtin.apt:
        update_cache: true
        name:
          - haproxy
      register: haproxy_new

    - name: Stop haproxy
      ansible.builtin.systemd_service:
        name: haproxy
        enabled: true
        state: stopped
      when: haproxy_new.changed

    - name: Ensure haproxy certs dir exists
      ansible.builtin.file:
        path: /etc/haproxy/certs
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: Copy certificate into haproxy certs directory
      ansible.builtin.copy:
        remote_src: true
        src: /etc/letsencrypt/live/combined.pem
        dest: /etc/haproxy/certs/cert.pem
        mode: "0600"
        owner: root
        group: root

    - name: Copy haproxy configuration
      ansible.builtin.template:
        src: proxmox-haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"
      register: haproxy_config

    - name: Restart haproxy
      ansible.builtin.systemd_service:
        name: haproxy
        enabled: true
        state: restarted
      when: haproxy_config.changed

    - name: Ensure haproxy is started
      ansible.builtin.systemd_service:
        name: haproxy
        enabled: true
        state: started

- name: Set up proxmox cluster
  hosts: proxmox_servers
  become: true
  roles:
    - role: lae.proxmox

- name: Proxmox post-config
  hosts: proxmox_servers
  become: true
  tasks:
    - name: Install useful packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - vim
          - tmux
          - htop
          - python3
          - python3-apt
          - python3-guestfs
          - python3-proxmoxer
          - python-is-python3
          - nfs-common
          - nfs4-acl-tools
          - libguestfs-tools
        state: present

    - name: Get debian image stats
      ansible.builtin.stat:
        path: /root/debian-12-amd64.qcow2
        checksum_algorithm: sha512
      register: deb_img_stat

    - name: Download Debian 12 genericcloud qcow2 image
      ansible.builtin.get_url:
        url: https://cloud.debian.org/images/cloud/bookworm/20241004-1890/debian-12-genericcloud-amd64-20241004-1890.qcow2
        dest: /root/debian-12-amd64.qcow2
        checksum: sha512:da84d609d7ec5645dae1df503ea72037b2a831401d1b42ce2e7ec2a840b699f07ca8aea630853a3d5430839268c2bd337be45d89498264c36a9b5e12872c59ee
        mode: "0644"
        owner: root
        group: root
      register: deb_img_new
      when: (deb_img_stat.stat.isreg is not defined) or (deb_img_stat.stat.isreg is defined and not deb_img_stat.stat.isreg)

    - name: Add cron to Debian 12 image
      vkhitrin.libguestfs.guestfs_package:
        image: /root/debian-12-amd64.qcow2
        name: cron
        state: present
      when: deb_img_new.changed

    - name: Add qemu-guest-agent to Debian 12 image
      vkhitrin.libguestfs.guestfs_package:
        image: /root/debian-12-amd64.qcow2
        name: qemu-guest-agent
        state: present
      when: deb_img_new.changed

    - name: Remove unattended-upgrades from Debian 12
      vkhitrin.libguestfs.guestfs_package:
        image: /root/debian-12-amd64.qcow2
        name: unattended-upgrades
        state: absent
      when: deb_img_new.changed

    - name: Copy /etc/network/interfaces config
      ansible.builtin.copy:
        src: debinterfaces
        dest: /tmp/debinterfaces
        owner: root
        group: root
        mode: "0644"
      when: deb_img_new.changed

    - name: Change network interfaces config for Debian 12
      vkhitrin.libguestfs.guestfs_copy_in:
        image: /root/debian-12-amd64.qcow2
        src: /tmp/debinterfaces
        dest: /etc/network/interfaces
      when: deb_img_new.changed

    - name: Create Debian 12 virtual machine
      community.general.proxmox_kvm:
        validate_certs: false # TODO: disable after figuring out LE certs
        api_user: root@pam
        api_password: failfail
        api_host: "{{ ansible_host }}"
        node: "{{ inventory_hostname }}"
        vmid: "{{ template_vmid2 }}"
        name: deb12-tmpl
        description: debian 12 template
        acpi: true
        cpu: cputype=SandyBridge
        cores: 1
        sockets: 1
        memory: 1024
        numa_enabled: true
        ostype: l26
        boot: c
        bootdisk: virtio0
        scsihw: virtio-scsi-pci
        ide:
          ide2: local-lvm:cloudinit,format=raw
        net:
          net0: virtio,bridge=vmbr0
        serial:
          serial0: socket
        vga: qxl
        agent: enabled=1,fstrim_cloned_disks=1
        hotplug: disk,network,usb,memory,cpu
        tags: [debian, bookworm, debian12, template]
        state: present
      when: deb_img_new.changed

    - name: Add root disk imported from qcow2 image to Debian 12 virtual machine
      community.general.proxmox_disk:
        validate_certs: false # TODO: disable after figuring out LE certs
        api_user: root@pam
        api_password: failfail
        api_host: "{{ ansible_host }}"
        vmid: "{{ template_vmid2 }}"
        name: deb12-tmpl
        disk: virtio0
        storage: local-lvm
        import_from: /root/debian-12-amd64.qcow2
        state: present
      when: deb_img_new.changed

    - name: Convert Debian 12 virtual machine to template
      community.general.proxmox_kvm:
        validate_certs: false # TODO: disable after figuring out LE certs
        api_user: root@pam
        api_password: failfail
        api_host: "{{ ansible_host }}"
        node: "{{ inventory_hostname }}"
        vmid: "{{ template_vmid2 }}"
        name: deb12-tmpl
        state: template
      when: deb_img_new.changed
