---
- name: Install and configure Sentry
  hosts: sentry
  become: true
  tasks:
    - name: Add Docker debian repo signed by gpg key
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        signed_by: https://download.docker.com/linux/debian/gpg
        uris: https://download.docker.com/linux/debian
        suites: bookworm
        components: [stable]
        enabled: true
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - ca-certificates
          - apt-transport-https
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Install git
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - git

    - name: Clone Sentry self-hosted repository
      ansible.builtin.git:
        repo: https://github.com/getsentry/self-hosted.git
        dest: /opt/sentry
        version: 24.7.1
        update: false
        single_branch: true

    - name: Run install script
      ansible.builtin.command:
        cmd: ./install.sh --report-self-hosted-issues --skip-user-creation
        chdir: /opt/sentry
        creates: /opt/sentry/geoip/GeoLite2-City.mmdb

    - name: Print reminder to create superuser
      ansible.builtin.debug:
        msg: Please run 'sudo docker compose run --rm web createuser' and answer yes to create a superuser
