---
- ansible.builtin.import_playbook: fog.yml
- ansible.builtin.import_playbook: apt-cacher-ng.yml
- ansible.builtin.import_playbook: postgres.yml
- ansible.builtin.import_playbook: mysql.yml
- ansible.builtin.import_playbook: influxdb.yml
- ansible.builtin.import_playbook: k3s-site.yml
...
