---
- ansible.builtin.import_playbook: proxmox.yml
- ansible.builtin.import_playbook: ntp-all.yml
- ansible.builtin.import_playbook: upgrade-all.yml
- ansible.builtin.import_playbook: pihole.yml
- ansible.builtin.import_playbook: fog.yml
- ansible.builtin.import_playbook: apt-cacher-ng.yml
- ansible.builtin.import_playbook: postgres.yml
- ansible.builtin.import_playbook: mysql.yml
- ansible.builtin.import_playbook: influxdb.yml
- ansible.builtin.import_playbook: grafana.yml
- ansible.builtin.import_playbook: prometheus.yml
- ansible.builtin.import_playbook: observium.yml
- ansible.builtin.import_playbook: sentry.yml
- ansible.builtin.import_playbook: gitlab.yml
# - ansible.builtin.import_playbook: k3s-site.yml
