---
# Set up proxmox hosts
- ansible.builtin.import_playbook: proxmox.yml
# Set up common stuff for all hosts
- ansible.builtin.import_playbook: ntp-all.yml
- ansible.builtin.import_playbook: upgrade-all.yml
# Set up the rest of the hosts
- ansible.builtin.import_playbook: pihole.yml
- ansible.builtin.import_playbook: keycloak.yml
# - ansible.builtin.import_playbook: stepca.yml # NOTE: fails due to upstream brokennes
- ansible.builtin.import_playbook: postgres.yml
- ansible.builtin.import_playbook: mysql.yml
- ansible.builtin.import_playbook: grafana.yml
# - ansible.builtin.import_playbook: prometheus.yml
- ansible.builtin.import_playbook: influxdb.yml
- ansible.builtin.import_playbook: gitlab.yml
- ansible.builtin.import_playbook: k3s-site.yml
# - ansible.builtin.import_playbook: netbox.yml # NOTE: upstream role is broken
# - ansible.builtin.import_playbook: gitlab-runners.yml # NOTE: haven't figured out how to fully automate this
- ansible.builtin.import_playbook: docker-runners.yml
