---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gitlab-agent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
      version: 2.12.2
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: gitlab-agent
  targetNamespace: gitlab-agent
  values:
    config:
      kasAddress: wss://kas.gitlab.com
      observability:
        enabled: false
      secretName: gitlab-agent-token
