- name: do basic setup for debian virtual machines
  hosts:
    - piholes
    - postgres
    - mysql
    - gitlab
    - k3s_cluster
    - k3s_single
  become: true

  tasks:
    - name: Wait for hosts to become reachable
      ansible.builtin.wait_for_connection:

    - name: update every debian virtual machine
      apt:
        upgrade: full
        update_cache: yes

    - name: INSTALL good packages
      apt:
        name:
          - vim
          - tmux
          - htop
          - stterm
          - qemu-guest-agent
          - python3
          - python3-apt
          - nfs-common
          - nfs4-acl-tools
        state:
          present

    - name: DELET this
      apt:
        name:
          - nano
        state:
          absent

    - name: Copy /etc/network/interfaces config
      copy:
        src: debinterfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
      register: netconfig

    - name: reboot hosts
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: netconfig.changed

    - name: wait for hosts to be up again
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300

- name: Install and configure NTP
  hosts: all
  become: True
  roles:
    - role: geerlingguy.ntp

- name: Install and slightly configure PostgreSQL
  hosts: postgres
  become: True
  roles:
    - role: geerlingguy.postgresql
      vars:
        postgresql_python_library: python3-psycopg2
        postgresql_service_state: started
        postgresql_service_enabled: true
        postgresql_locales:
          - 'en_US.UTF-8'
        #TODO: Check if the following works
        #postgresql_databases:
        #  - name: testpostgresdb
        #    login_host: # defaults to 'localhost'
        #    login_password: # defaults to not set
        #    login_user: # defaults to 'postgresql_user'
        #    owner: testpostgresuser
        #postgresql_users:
        #  - name: testpostgresuser
        #    password: testpostgresuserpassword123
        #    priv: # defaults to not set
        #    role_attr_flags: # defaults to not set
        #    db: testpostgresdb
        #    login_host: # defaults to 'localhost'
        #    login_password: # defaults to not set
        #    login_user: # defaults to '{{ postgresql_user }}'

- name: Install and slightly configure MySQL
  hosts: mysql
  become: True
  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_root_password_update: true
        mysql_root_password: mysqladmin123
        #TODO: Check if the following works
        #mysql_databases:
        #  - name: testmysqldb
        #mysql_users:
        #  - name: "{{ mysql_root_user }}"
        #    password: "{{ mysql_root_password }}"
        #  - name: testmysqluser
        #    host: "%"
        #    password: testmysqluserpassword123
        #    priv: "testmysqldb.*:ALL"

- name: Build a k3s cluster with a single control node
  hosts: k3s_cluster
  #vars:
  #  k3s_state: uninstalled
  roles:
    - role: xanmanning.k3s

- name: Build single-node k3s cluster
  hosts: k3s_single
  #vars:
  #  k3s_state: uninstalled
  roles:
    - role: xanmanning.k3s
