- name: Install and configure NTP
  hosts: all
  become: True
  roles:
    - role: geerlingguy.ntp
      vars:
        ntp_manage_config: true
        ntp_servers:
          - 10.0.50.254 iburst
          - 0.debian.pool.ntp.org
          - 1.opnsense.pool.ntp.org
          - 2.opnsense.pool.ntp.org
          - 3.debian.pool.ntp.org

- name: Install and slightly configure PostgreSQL
  hosts: postgres
  become: True
  roles:
    - role: geerlingguy.postgresql
      vars:
        postgresql_python_library: python3-psycopg2
        postgresql_locales:
          - 'en_US.UTF-8'

- name: Install and slightly configure MySQL
  hosts: mysql
  become: True
  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_root_password: mysqladmin123

- name: Build a k3s cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become: true
  roles:
    - role: xanmanning.k3s
