---
k3s_version: v1.17.5+k3s1
ansible_user: angle
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: --datastore-endpoint 'mysql://k3s:flagrant@tcp(192.168.5.1:3306)/k3s'
extra_agent_args: ""
