---
originRequest:
  originServerName: "nginx.inherently.xyz"

ingress:
  - hostname: "*.inherently.xyz"
    service: &svc https://ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
