---
- name: Unload nmi_watchdog
  community.general.modprobe:
    name: nmi_watchdog
    state: absent

- name: Attempt to unload softdog live
  community.general.modprobe:
    name: softdog
    state: absent
  ignore_errors: true
  register: _pve_rmmod_softdog

- when: _pve_rmmod_softdog is failed

  block:
    - name: Stop watchdog-mux
      ansible.builtin.service:
        name: watchdog-mux
        state: stopped
      notify:
        - restart watchdog-mux

    - name: Unload softdog
      community.general.modprobe:
        name: softdog
        state: absent
- name: Disable nmi_watchdog via GRUB config
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX nmi_watchdog=0"
    insertafter: ^GRUB_CMDLINE_LINUX="
  register: _pve_grub

- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  register: _pve_grub_update
  failed_when: ('error' in _pve_grub_update.stderr)
  when: _pve_grub is changed
  tags: skiponlxc
