---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.11.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      electionTTL: 15s
      ingressClassResource:
        default: true
        enabled: true
      maxUnavailable: 1
      publishService:
        enabled: true
      replicaCount: 3
      service:
        annotations:
          metallb.universe.tf/address-pool: server-vlan-pool
          metallb.universe.tf/loadBalancerIPs: 10.0.50.150
        enabled: true
        external:
          enabled: true
        externalTrafficPolicy: Local
      terminationGracePeriodSeconds: 300
      updateStrategy:
        type: RollingUpdate
      watchIngressWithoutClass: true
