---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flink
  namespace: &ns analytics
spec:
  chart:
    spec:
      chart: flink-kubernetes-operator
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: flink-operator
        namespace: *ns
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    webhook:
      create: false
