apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone-server
  namespace: drone
spec:
  rules:
  - host: drone.kates.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: droneserver
            port:
              number: 80
