apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_SERVER: http://gitea.kates.test
  DRONE_SERVER_HOST: drone.kates.test
  DRONE_GITEA_CLIENT_ID: f8e4ab41-4020-414b-9db9-3b353d9488df
  DRONE_GITEA_CLIENT_SECRET: MhF8eLfc0uymSDFLqZ2f8SoWlKUdtpdVMm8vy3bS2js=
  DRONE_RPC_SECRET: e96b5ac2e20e89eaee6bf49c03948ebb
  DRONE_DATABASE_DATASOURCE: postgres://droneciuser:DRONEs-CIrcling-4b0v3@postgres:5432/dronecidb?sslmode=disable
  DRONE_USER_CREATE: username:inherently,admin:true
