---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: v1.15.3
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    cainjector:
      enabled: true
      podDisruptionBudget:
        enabled: true
        maxUnavailable: 1
      replicaCount: 2
      strategy:
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
        type: RollingUpdate
    crds:
      enabled: true
      keep: true
    dns01RecursiveNameservers: ""
    dns01RecursiveNameserversOnly: false
    enableCertificateOwnerRef: true
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    prometheus:
      enabled: false
    replicaCount: 2
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    webhook:
      podDisruptionBudget:
        enabled: true
        maxUnavailable: 1
      replicaCount: 2
      strategy:
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
        type: RollingUpdate
