---

- name: get proxie moxie dressed right
  hosts: all
  become: true

  tasks:
    - name: remove garbo enterprise repo
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: no-sub squad gang
      copy:
        src: files/pve-no-sub.list
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        mode: '0644'
        owner: root
        group: root

    - name: get debbie could image
      get_url:
        name: http://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2
        dest: /root/debian-10-openstack-amd64.qcow2
        mode: '0644'
        owner: root
        group: root


    - name: move templ vm scriptoid
      copy:
        src: files/setup-debian-template.sh
        dest: /root/setup-debian-template.sh
        mode: '0755'
        owner: root
        group: root

    # TODO: replace with ansible proxmox module
    - name: run templ vm scriptoid
      shell:
        cmd: /root/setup-debian-template.sh
