---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitlab-agent
  namespace: &ns default
spec:
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
      version: 2.12.2
  interval: 10m
  releaseName: *app
  targetNamespace: *ns
  values:
    config:
      kasAddress: wss://kas.gitlab.com
      observability:
        enabled: false
      secretName: gitlab-agent-token
