---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: 0.14.8
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: metallb
  targetNamespace: metallb-system
  values:
    controller:
      enabled: true
    crds:
      enabled: true
      validationFailurePolicy: Fail
    frrk8s:
      enabled: false
      external: false
    rbac:
      create: true
    speaker:
      enabled: true
      frr:
        enabled: false
