# Permalink: https://github.com/metallb/metallb/blob/110fbf0e47379d8af847b8dc31ec1751cdf6139d/charts/metallb/values.yaml

rbac:
  # create specifies whether to install and use RBAC rules.
  create: true

# controller contains configuration specific to the MetalLB cluster
# controller.
controller:
  enabled: true

# speaker contains configuration specific to the MetalLB speaker
# daemonset.
speaker:
  enabled: true
  # frr contains configuration specific to the MetalLB FRR container,
  # for speaker running alongside FRR.
  frr:
    enabled: false

crds:
  enabled: true
  validationFailurePolicy: Fail

# frrk8s contains the configuration related to using an frrk8s instance
# (github.com/metallb/frr-k8s) as the backend for the BGP implementation.
# This allows configuring additional frr parameters in combination to those
# applied by MetalLB.
frrk8s:
  # if set, enables frrk8s as a backend. This is mutually exclusive to frr
  # mode.
  enabled: false
  external: false
