- name: Install CloudFlare certbot plugin
  ansible.builtin.apt:
    name: python3-certbot-dns-cloudflare
    update_cache: true
    state: present

- name: Create cloudflare credentials file
  ansible.builtin.template:
    src: cloudflare.ini.j2
    dest: /etc/ssl/cloudflare.ini
    mode: "0600"
    owner: root
    group: root

- name: Get LetsEncrypt TLS certificates
  ansible.builtin.import_role:
    name: geerlingguy.certbot
  vars:
    certbot_install_method: package
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_auto_renew_user: root
    certbot_admin_email: pepitsizous@zoho.com
    certbot_certs:
      - domains: "{{ cloudflare_cert_domains }}"
    certbot_create_command: "{{ certbot_script }} certonly --preferred-challenges dns --dns-cloudflare --dns-cloudflare-credentials /etc/ssl/cloudflare.ini --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }} --dns-cloudflare-propagation-seconds 39"

- name: Copy certificate into target directory
  ansible.builtin.copy:
    remote_src: true
    src: "/etc/letsencrypt/live/{{ cloudflare_cert_domains[0] }}/fullchain.pem"
    dest: "{{ cloudflare_cert_file_dest }}"
    mode: "0644"
    owner: root
    group: root

- name: Copy private key into target directory
  ansible.builtin.copy:
    remote_src: true
    src: "/etc/letsencrypt/live/{{ cloudflare_cert_domains[0] }}/privkey.pem"
    dest: "{{ cloudflare_key_file_dest }}"
    mode: "0644"
    owner: root
    group: root
