---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx
  namespace: &ns network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: metallb-l2advert
      namespace: *ns
  interval: 10m
  path: ./fluxcd/homecluster/apps/network/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  timeout: 5m
  wait: true
