---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 4.1.3
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: openebs
  targetNamespace: openebs
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    lvm-localpv:
      crds:
        csi:
          volumeSnapshots:
            enabled: false
        lvmLocalPv:
          enabled: false
    mayastor:
      crds:
        enabled: false
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        clusterDomain: cluster.local
      io_engine:
        envcontext: iova-mode=pa
      localpv-provisioner:
        enabled: false
      loki-stack:
        enabled: false
        promtail:
          enabled: false
        rbac:
          create: false
      obs:
        callhome:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: true
    zfs-localpv:
      crds:
        csi:
          volumeSnapshots:
            enabled: false
        zfsLocalPv:
          enabled: false
