# https://raw.githubusercontent.com/openebs/openebs/e90fe9b35ea45ca03077317259e8eb530693ad33/charts/values.yaml
mayastor:
  csi:
    node:
      initContainers:
        enabled: false # NOTE: required by Talos
  etcd:
    # -- Kubernetes Cluster Domain
    clusterDomain: cluster.local
  localpv-provisioner:
    enabled: false
  crds:
    enabled: false
  loki-stack:
    enabled: false
    promtail:
      enabled: false
    rbac:
      create: false
  obs:
    callhome:
      enabled: false
  # NOTE: https://github.com/openebs/mayastor/issues/1763
  io_engine:
    envcontext: "iova-mode=pa"

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: true

openebs-crds:
  csi:
    volumeSnapshots:
      enabled: true
      keep: true

lvm-localpv:
  crds:
    lvmLocalPv:
      enabled: false
    csi:
      volumeSnapshots:
        enabled: false

zfs-localpv:
  crds:
    zfsLocalPv:
      enabled: false
    csi:
      volumeSnapshots:
        enabled: false
