all:
  children:
    mysql:
      hosts:
        10.0.50.23:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          ntp_manage_config: true
          ntp_servers: &id001
          - 10.0.50.254 iburst
          - 0.debian.pool.ntp.org
          - 1.opnsense.pool.ntp.org
          - 2.opnsense.pool.ntp.org
          - 3.debian.pool.ntp.org
          timezone: Europe/Athens
    piholes:
      hosts:
        10.0.50.2:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          ntp_manage_config: true
          ntp_servers: *id001
          timezone: Europe/Athens
    postgres:
      hosts:
        10.0.50.20:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          ntp_manage_config: true
          ntp_servers: *id001
          timezone: Europe/Athens
    pve:
      children:
        pve0:
          hosts:
            10.0.50.70:
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: root
              interfaces_template: ''
              ntp_manage_config: true
              ntp_servers: *id001
              ntp_timezone: Europe/Athens
              pve_group: optiplex
              pve_groups: &id002
              - comment: Administrators of this PVE cluster
                name: admins
              - comment: API Enjoyers
                name: api_users
              - comment: Fodder
                name: test_users
              pve_ssh_port: 22
              pve_storages: &id003
              - content:
                - images
                - iso
                - backup
                export: /mnt/tank-z1/nfs-proxmox
                name: proxmox-nfs
                server: 10.0.50.142
                type: nfs
              timezone: Europe/Athens
        pve1:
          hosts:
            10.0.50.71:
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: root
              interfaces_template: ''
              ntp_manage_config: true
              ntp_servers: *id001
              ntp_timezone: Europe/Athens
              pve_group: optiplex
              pve_groups: *id002
              pve_ssh_port: 22
              pve_storages: *id003
              timezone: Europe/Athens
        pve2:
          hosts:
            10.0.50.72:
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: root
              interfaces_template: ''
              ntp_manage_config: true
              ntp_servers: *id001
              ntp_timezone: Europe/Athens
              pve_group: optiplex
              pve_groups: *id002
              pve_ssh_port: 22
              pve_storages: *id003
              timezone: Europe/Athens
    ungrouped: {}
