all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            10.0.50.51:
              ansible_host: 10.0.50.51
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              k3s_become: true
              k3s_control_node: true
              k3s_debug: false
              k3s_etcd_datastore: true
              k3s_install_hard_links: true
              k3s_release_version: v1.27.3+k3s1
              k3s_server:
                cluster-cidr: 172.13.0.0/16
                disable:
                - servicelb
                - traefik
                disable-cloud-controller: true
                docker: false
                etcd-expose-metrics: true
                kube-apiserver-arg:
                - anonymous-auth=true
                kube-controller-manager-arg:
                - bind-address=0.0.0.0
                kube-proxy-arg:
                - metrics-bind-address=0.0.0.0
                kube-scheduler-arg:
                - bind-address=0.0.0.0
                node-ip: '{{ ansible_host }}'
                service-cidr: 192.168.8.0/22
                tls-san:
                - '{{ ansible_host }}'
                write-kubeconfig-mode: '644'
              k3s_server_manifests_urls: &id001
              - filename: metallb-native.yaml
                url: https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
              k3s_use_experimental: true
              k3s_use_unsupported_config: true
              ntp_manage_config: true
              ntp_servers: &id002
              - 10.0.50.254 iburst
              - 0.debian.pool.ntp.org
              - 1.opnsense.pool.ntp.org
              - 2.opnsense.pool.ntp.org
              - 3.debian.pool.ntp.org
              timezone: Europe/Athens
        node:
          hosts:
            10.0.50.61:
              ansible_host: 10.0.50.61
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              k3s_become: true
              k3s_debug: false
              k3s_etcd_datastore: true
              k3s_install_hard_links: true
              k3s_release_version: v1.27.3+k3s1
              k3s_server_manifests_urls: *id001
              k3s_use_experimental: true
              k3s_use_unsupported_config: true
              ntp_manage_config: true
              ntp_servers: *id002
              timezone: Europe/Athens
            10.0.50.62:
              ansible_host: 10.0.50.62
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              k3s_become: true
              k3s_debug: false
              k3s_etcd_datastore: true
              k3s_install_hard_links: true
              k3s_release_version: v1.27.3+k3s1
              k3s_server_manifests_urls: *id001
              k3s_use_experimental: true
              k3s_use_unsupported_config: true
              ntp_manage_config: true
              ntp_servers: *id002
              timezone: Europe/Athens
            10.0.50.63:
              ansible_host: 10.0.50.63
              ansible_private_key_file: /home/angle/.ssh/id_rsa
              ansible_python_interpreter: /usr/bin/env python3
              ansible_user: debian
              k3s_become: true
              k3s_debug: false
              k3s_etcd_datastore: true
              k3s_install_hard_links: true
              k3s_release_version: v1.27.3+k3s1
              k3s_server_manifests_urls: *id001
              k3s_use_experimental: true
              k3s_use_unsupported_config: true
              ntp_manage_config: true
              ntp_servers: *id002
              timezone: Europe/Athens
    mysql:
      hosts:
        10.0.50.23:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          ntp_manage_config: true
          ntp_servers: *id002
          timezone: Europe/Athens
    piholes:
      hosts:
        10.0.50.2:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          ntp_manage_config: true
          ntp_servers: *id002
          timezone: Europe/Athens
    postgres:
      hosts:
        10.0.50.20:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: debian
          ntp_manage_config: true
          ntp_servers: *id002
          timezone: Europe/Athens
    pve:
      hosts:
        10.0.50.71:
          ansible_private_key_file: /home/angle/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/env python3
          ansible_user: root
          interfaces_template: ''
          ntp_manage_config: true
          ntp_servers: *id002
          pve_cluster_enabled: false
          pve_group: optiplex
          pve_groups:
          - comment: Administrators of this PVE cluster
            name: admins
          - comment: API Enjoyers
            name: api_users
          - comment: Fodder
            name: test_users
          pve_reboot_on_kernel_update: true
          pve_remove_subscription_warning: true
          pve_repository_line: deb http://download.proxmox.com/debian/pve bullseye
            pve-no-subscription
          pve_ssh_port: 22
          pve_storages:
          - content:
            - images
            - iso
            export: /mnt/tank-z1/nfs-proxmox
            name: proxmox-nfs
            server: 10.0.50.142
            type: nfs
          timezone: Europe/Athens
    ungrouped: {}
