apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-triple-replica
  annotations:
    storageclass.kubernetes.io/is-default-class: true
parameters:
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
