apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-suzuhara-config
data:    
  server.properties: |
    generator-settings=
    use-native-transport=true
    op-permission-level=4
    allow-nether=true
    level-name=suzuhara
    enable-query=false
    allow-flight=false
    prevent-proxy-connections=false
    server-port=25565
    max-world-size=29999984
    level-type=DEFAULT
    enable-rcon=false
    level-seed=konlulu
    force-gamemode=false
    server-ip=
    network-compression-threshold=256
    max-build-height=256
    spawn-npcs=true
    white-list=false
    spawn-animals=true
    hardcore=false
    snooper-enabled=false
    resource-pack-sha1=
    online-mode=false
    resource-pack=
    pvp=false
    difficulty=0
    enable-command-block=false
    gamemode=0
    player-idle-timeout=0
    max-players=20
    spawn-monsters=true
    generate-structures=true
    view-distance=10
    motd=kubecraft
