---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: world-pvc
spec:
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 22Gi
